### ISSUE TITLE
[Engines] Handling the lifecycle logic of the .hdbsequence artifact

### ISSUE THREAD

**Issue by GrozevJunior** [SAP/xsk#100]
1. Create manger service
2. Add it to the CoreFacade
3. Make a corresponding model
4. Implement processors CREATE, DROP, ALTER
5. Take the hana syntax version into consideration

**Comment by delchev** [comment]
Depends on: https://github.com/eclipse/dirigible/issues/764

**Comment by Wildflowerr** [comment]
Fixed with: https://github.com/SAP/xsk/pull/113/commits/27129d80f25d2af3f3f254173c96c9f1ce6fe059
