### ISSUE TITLE
[Migration] Default hdbrole for all analytic privileges

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1014]
### Background
The recommended approach to assigning analytic privileges is to do it via roles. As there will be one technical user that needs these privileges assigned, this can be handled by XSK behind the scenes.

### Target
**Note: this hdbrole must have a special name that XSK knows and processes it with special logic. Only hdbrole with name `xsk_technical_privileges` must be processed with the logic below!**

1. Determine all analytic privileges in the project
2. Create an hdbrole containing all the analytic privileges like so:
xsk_technical_privileges.hdbrole
```json
{
  "role": {
    "name": "xsk_technical_privileges",
    "schema_analytic_privileges": [
      {
        "privileges": [
          "<id_privilege1>",
          "<id_privilege2>",
          ...
        ]
      }
    ]
  }
}
```
3. Add this file to be deployed in the hdi container (`deploy` array in `.hdi` file)
4. Process this file while deploying content to the container so that post-deploy, the role is assigned to the HANA_USER with which the db connection is made (see [help doc](https://help.sap.com/viewer/6a504812672d48ba865f4f4b268a881e/Cloud/en-US/6574d8eb496c4f2f9f023237abb6c87a.html))
```sql
CREATE LOCAL TEMPORARY COLUMN TABLE #ROLES LIKE _SYS_DI.TT_SCHEMA_ROLES;
INSERT INTO #ROLES ( ROLE_NAME, PRINCIPAL_SCHEMA_NAME, PRINCIPAL_NAME ) VALUES ( 'xsk_technical_privileges', '', '<HANA_USER>' );
CALL <container>#DI.GRANT_CONTAINER_SCHEMA_ROLES(.#ROLES, _SYS_DI.T_NO_PARAMETERS, ?, ?, ?);
DROP TABLE .#ROLES; 
```

### Delete case
When the hdbrole is being unpublished, unassign the role from the technical user as described in the [SAP Documentation](https://help.sap.com/viewer/6a504812672d48ba865f4f4b268a881e/Cloud/en-US/bb47fc06c27841449017d055302a4074.html)

**Comment by ThuF** [comment]
@dpanayotov how about **`xsk_technical_privileges`** instead of **`technical_privileges`**?

**Comment by dpanayotov** [comment]
Agree. Description is adjusted

**Comment by tdermendjiev** [comment]
When the role is undeployed it's automatically deleted.

**Comment by MarinHadzhiev** [comment]
implemented with https://github.com/SAP/xsk/pull/1747
