### ISSUE TITLE
[Test] Integration test fails

### ISSUE THREAD

**Issue by ivanvolkoff** [SAP/xsk#1015]
Integration tests are executed against Chrome and Firefox browsers. If we initiate the tests and after the test passes successfully in the first browser (Chrome) then the test in the second one fails, with the error "Git repository already exist".

Related to : #998

**Comment by ThuF** [comment]
This could be related to a recent change in Eclipse Dirigible (part of the **6.1.17** release): https://github.com/eclipse/dirigible/commit/5eed856dd795a62afb9c619fb22fe233510d62b2

With this commit the location where git projects are cloned was changed as follows:
- `.../target/.git` &#8594; `.../target/dirigible/repository/.git`
