### ISSUE TITLE
[Parsers] Check if common parser state interferes in migration / synchronising

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#1028]
When using the `Hdbdd` parser from the migration process, the state of the parser is saved with the parsing done on the delivery unit files inside the temporary directory, created during migration. This cached data `might` interfere with the parsing done on a later stage inside the workspace by the synchroniser.

Scenario:
1. Migrate application (with hdbdd)
2. Publish app (check in HANA Cloud that the tables are created)
3. Delete and unpublish 
4. In HANA @ Neo change the hdbdd (e.g. have a second table)
5. Trigger a new migration
6. Publish again
7. Check if the new table exists in HANA Cloud

**Comment by dpanayotov** [comment]
obsolete
