### ISSUE TITLE
[Parsers] No parser is called for hdbtabletype artifacts and when called schema is returned as null

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#1029]
During migration, when attempting to parse the following `publishers.hdbtabletype` artifact: 
```
TYPE "XSK_SAMPLES_HDI_CUBE"."customer_sample::publishers" AS TABLE (
   "PUBLISHER" INTEGER, 
   "NAME" NVARCHAR(50), 
   "PRICE" DECIMAL, 
   "COUNT" INTEGER 
)
```
No parser from the parserServices was found for the artifact.
After adding a (what seems to be missing) binding from XSKTableTypeParser to the `.hdbtabletype` extension [here](https://github.com/SAP/xsk/blob/main/modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/module/XSKHDBModule.java#:~:text=parserServices.put(IXSKDataStructureModel,FILE_EXTENSION_STRUCTURE%2C%20new%20XSKTableTypeParser())%3B). </br> The parser was called, but the XSKDataStructureHDBTableTypeModel returned had a null schema.

**Comment by Fluctuationqt** [comment]
Debugging this issue i noticed that the schema is not obtained when XSKTableTypeParser::parse() is called. 

* Stack:
> XSKTableTypeParser::parse(...)
>> XSKTableTypeParser::parseHanaXSAdvancedContent(...) 
>>>  public static void populateXSKDataStructureModel(...) {

* Implementation (missing set schema):
```
public static void populateXSKDataStructureModel(String location, String content, XSKDataStructureModel model, String artifactType, XSKDBContentType DbContentType) {
        model.setName(XSKCommonsUtils.getRepositoryBaseObjectName(location));
        model.setLocation(location);
        model.setType(artifactType);
        model.setHash(DigestUtils.md5Hex(content));
        model.setCreatedBy(UserFacade.getName());
        model.setCreatedAt(new Timestamp(new java.util.Date().getTime()));
        model.setDbContentType(DbContentType);
}
```

**Comment by vmutafov** [comment]
Fixed with: https://github.com/SAP/xsk/pull/1396
