### ISSUE TITLE
[Migration] Projects represented as git projects

### ISSUE THREAD

**Issue by ivanvolkoff** [SAP/xsk#1031]
After migration projects are represented in the workspace as git projects.
<img width="333" alt="Screenshot 2022-01-19 at 13 21 50" src="https://user-images.githubusercontent.com/61655573/150121105-7b100ca7-00c3-408b-8aa6-885883619c08.png">
.

**Comment by vmutafov** [comment]
This is expected and the projects should be marked as git projects.
