### ISSUE TITLE
[Migration] Support importing XSK projects from a zip

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1048]
Currently, the migration perspective supports only connecting to a HANA 1 instance and migrating delivery units from it. In some cases, there might be no way to connect to such an instance and we should support manually importing a zip having an XS project. This would also make it easier for local development.

**Frontend changes:**
We should implement some additional screen before the one for entering Neo credentials where the user would decide if he wants to migrate a project from a HANA 1 instance or from a local zip. It would probably be sufficient to have two radio buttons:
- Migrate a project from a local ZIP archive
- Migrate a project from a live HANA instance
Based on the user input, we would either go to the current Neo credentials screen or a new one having a drag n drop file chooser similar to the one used in the Dirigible for importing projects in a workspace.
The drag n drop screen should also have the same workspace selection dropdown as in the other migration screens.

**Backend changes:**
The Flowable process should also be modified in order to support this functionality. We would need to "bypass" the tasks for connecting to the HANA and fetching content from it. 

Please, contact me when the frontend changes are done in order to discuss thoroughly the backend changes and split the work if necessary.

**Comment by dimitarquanterall** [comment]
Please, assign it to me
