### ISSUE TITLE
[Releng] Runtime-only setup

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1050]
### Background
Currently, the setup of XSK results in both a design-time (web ide) and runtime (serving files). For running the applications in a productive setup only the runtime must be available to run as an immutable docker container.

### Target
Prepare a build of XSK with only the runtime, without the designtime. See https://github.com/eclipse/dirigible/tree/master/releng/sap-kyma-runtime
TBD how to package the source code of the application as well

Exclude neo-sdk (TBD more)

**Prerequisite**
 Only migrated code works with this image. If application has old syntax it needs to go through the migration process.

**Checks**
1. Application source code is bundled with xsk-runtime-image
2. HDB artifacts are being published to HANA Cloud
3. xsjs, xsjslib and xsodata can serve requests as usual (connection to HANA Cloud, query db, calcviews, analytic privileges, etc.)
4. Multiple instances of this container can run at the same time without interference
5. Authentication and authorization work with XSUAA (service bound to the container)
6. Destination service integration works (service bound to the container)
7. Restart (start/stop) of a container does not interfere with the HANA database

**Comment by ThuF** [comment]
Buildpack or Kpack, could be possible solutions for bundling the application code with the XSK runtime. Reference could be found here: https://github.com/SAP/xsk/tree/main/releng/buildpacks/xsk-kyma

More native approach would be to build docker image via Dockerfile, as described here: https://blogs.sap.com/2020/11/19/eclipse-dirigible-building-application-docker-image/
