### ISSUE TITLE
[Documentation] Overview page with all artefacts

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1051]
### Target
Prepare a page in xsk.io with a table showing the artefacts in SAP HANA and whether they are supported by XSK.

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/SAP/xsk/pull/1049

**Comment by ThuF** [comment]
- https://www.xsk.io/artefacts/
- https://www.xsk.io/cheatsheet/hdi/
