### ISSUE TITLE
[CI/CD] Pipeline for automatically delivery

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#1052]
Pipeline for XSK on KYMA on BTP with different requirements, APIs and etc. 

### Target
Prepare a template for github actions that does the following:
1. Acts on new release
2. Pulls the sources from the repo
3. Builds a new docker image with base xsk-runtime
4. Pushes the image to a predefined docker registry

Steps 3-7 from the following diagram
![xsk-lm-standalone](https://user-images.githubusercontent.com/4910295/151165320-2c3ac9fe-ff56-42b8-bfb3-8fb76d7fdda6.png)

**Comment by alexkuklin** [comment]
I've considered automating xsk deployment and found out it may pose security risks if implemented on customers' systems.

We need to mitigate that risk with image signing and admission control in client k8s cluster.

This task breaks down to those:
- implement docker image signing and define review and sign policies
- deploy admission controller or policy with  OPA/Gatekeeper or Connaisseur 
- create role definition for deployment agent to be applied on customers
- create some pull or push mechanism triggering deployment update on new versoin release

Given some thought, I suppose pull-type mechanism run and controlled on client systems would be preferred as it transfers manageability to customer.

**Comment by alexkuklin** [comment]
For local xsk image just adding application to `/usr/local/tomcat/target/dirigible/repository/root/users/dirigible/workspace/` worked fine at first look, yet for kyma deployed instance there's no way to tell what user will it be.

As we discussed it with developers, application should be added to repository dir for further publishing within the system.
Checking that out.

**Comment by ThuF** [comment]
Hi @alexkuklin,

The applications should be added into the _Public Registry_: `/usr/local/tomcat/target/dirigible/repository/root/registry/public`

Regards,
Yordan

**Comment by dpanayotov** [comment]
@alexkuklin please upload workflow in SAP/xsk

**Comment by dpanayotov** [comment]
depends on 
- #1050 

To be adjusted when the runtime image is available

**Comment by krasimirdermendzhiev** [comment]
Runtime image is available - dirigiblelabs/xsk-kyma-runtime-distro

**Comment by dpanayotov** [comment]
fixed with #1784
