### ISSUE TITLE
[Documentation] Describe behaviour of analytic privileges

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1058]
### Target
Prepare a page on xsk.io under artefacts for hdbanalyticprivilege and document behaviour changes related to `SESSION_USER` context variable and that it needs to be `SESSION_CONTEXT('APPLICATIONUSER')`

**Comment by dpanayotov** [comment]
related to #1014

**Comment by ThuF** [comment]
Fixed with: https://github.com/SAP/xsk/pull/1466
