### ISSUE TITLE
[Core] Unpublish - When artifact is unpublished/deleted the db data structure stays present

### ISSUE THREAD

**Issue by GrozevJunior** [SAP/xsk#107]
When you delete an artifact(.hdbtable, .hdbti, .hdbview etc.) form the dirigible explorer the data structure associated to it should be dropped from the database as well.

**Comment by ThuF** [comment]
The drop behaviour should be triggered on `Unpublish`

**Comment by ThuF** [comment]
Confirm dialog for HDB related artefacts, whether to be deleted from the Data Structures Table. To be implemented in Eclipse Dirigible and to be ported in XSK.

**Comment by delchev** [comment]
related to dev scenario, so lower priority for now and postpone the issue

**Comment by ThuF** [comment]
Initial unpublish metadata behaviour is being implemented with: https://github.com/eclipse/dirigible/pull/1338
Progress tracked in: https://github.com/SAP/xsk/pull/883

**Comment by dpanayotov** [comment]
Remaining work in #666
