### ISSUE TITLE
[Migration] Better parser error handling during migration

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#1077]
If a parser exception occurs during migration, the delivery unit file iteration will break.
Only the files copied before the exception go to the workspace and the migration looks like it passed successfully, 
but files and projects are missing.

edit @dpanayotov:
- show warnings at the diff stage of the migration which files couldn't be processed and that they should be manually checked

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
