### ISSUE TITLE
[HDBDD][Parser] User defined annotations support

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1092]
Error message in the `Problems` view:

`Error at line: 7 - 'annotation' is not a valid artifact type.`

```
namespace sap.hana.demo.app.data;

@Schema: 'DEMO'
context APP {

  type SDate : LocalDate;
  annotation MyAnnotation: String(40);

  Type ValidityT {
    StartDate : SDate; 
    EndDate   : SDate;
  };

}
```

Hdbdd is being parsed successfully by the antlr4 grammar but during the processing of the user defined annotation data type an error for not valid artifact occurs as the `annotation` type is not supported in the `SymbolTypeEnum`. 

Information on user defined annotations can be found [here](https://help.sap.com/viewer/09b6623836854766b682356393c6c416/2.0.03/en-US/fd2a79e92a374d3596950d97f5386ba8.html)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
