### ISSUE TITLE
[HDBDD][Parser] Series data support

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1093]
Error in the `Problems` view:

`no viable alternative at input 'series('`

```
namespace test;

context SeriesData {
    entity MySeriesEntity1 {
        key setId : Integer;
        t : UTCTimestamp;
        value : Decimal(10,4);
        series (
            series key (setId)
            period for series (t)
            equidistant increment by interval 0.1 second
        );
    };    
};
``` 
Support for series data should be implemented - [reference](https://help.sap.com/viewer/09b6623836854766b682356393c6c416/2.0.06/en-US/ad036c56b5e545ae8b31ece0ab95379f.html?q=series%20data#loioad036c56b5e545ae8b31ece0ab95379f__section_q1n_2lt_yr).

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
