### ISSUE TITLE
Login flow broken locally

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1106]
version: latest from main
Setup: locally built jar running on tomcat

What's going on:
1. index-busy is not loaded anymore
2. dirigible login screen is shown
3. after entering the credentials, the page refreshes and I'm again presented with login form
4. I enter the credentials again (assuming something happened) and I'm redirected to `http://localhost:8080/services/v4/web/ide/j_security_check` and I see response `{"message":"Resource not found: ide/j_security_check","status":404}`
5. If i try to again navigate `http://localhost:8080/` I'm redirected to the login screen again
6. If I refresh the page `http://localhost:8080/services/v4/web/ide/` then XSK loads

**Comment by ThuF** [comment]
Possible implementation state:
- https://github.com/eclipse/dirigible/blob/master/modules/core/core-scheduler/src/main/java/org/eclipse/dirigible/core/scheduler/api/AbstractSynchronizer.java#L240-L282
