### ISSUE TITLE
[IDE] CSV Editor - Add support for ~ 

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1111]
`CSV` files where the `~` symbol is used as delimiter are not displayed correctly in the `CSV Editor` - all values are are displayed in a single column per row.

**file.csv**:
```csv
Column1~Column2~Column3
101~ABCD~Text1234
101~QWER~Text5678
102~QAZW~Abcd1234
```

Related to: 
- https://github.com/SAP/xsk/issues/1110

**Comment by dimitarquanterall** [comment]
Please, assign to me
