### ISSUE TITLE
[IDE] CSV Editor - Total Records Count

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1117]
It would be great if the CSV editor is displaying the total records count somewhere:

**Sample rows count:**
![sample-csv-data](https://user-images.githubusercontent.com/4092083/151515240-a714938c-1ea1-4507-b8ce-c62bf64c6eac.png)

**CSV Editor:**
![csv-editor](https://user-images.githubusercontent.com/4092083/151515549-2131e8f9-9ddc-4560-9f0c-f2d7e3affa89.png)

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1488

**Comment by dimitarquanterall** [comment]
Please, assign it to me

**Comment by dimitarquanterall** [comment]
It seems to have been merged in dirigible/main
