### ISSUE TITLE
[Migration] Remove the dependency for Java 8 for the Neo SDK

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1120]
Currently, we ship a Java 8 runtime as the Neo SDK commands depend on JAXB classes which are removed in Java 11+. 
There is another way to circumvent these issues. We can provide the Neo SDK with the necessary JAXB JARs and it should work as expected.

**Comment by ThuF** [comment]
Fixed with: https://github.com/SAP/xsk/pull/1113
