### ISSUE TITLE
[Database] Implementation of the “copy” approach for hdbtable

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#114]
Implementation of the “copy” approach for hdbtable in case of incompatible changes on existing and non-empty table. The feature to be configurable via env var.

**Comment by Wildflowerr** [comment]
Altering on non-empty hdbtable is now possible when changes are compatible. However,  **altering "strategies"** have not yet been implemented.

**Comment by dpanayotov** [comment]
not relevant anymore
