### ISSUE TITLE
[UI] Adopt fundamental styles - view Migration Launch

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1144]
### Target
- [ ] Adopt the fundamental styles in Migration Launch view

Use https://github.com/dirigiblelabs/ide-next as reference

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1505

**Comment by StanZGenchev** [comment]
The new design will split the Migration perspective into 3 separate views. History, Zip migration and Live migration.

History:

This should be the main view. In the top panel, there should be a dropdown, allowing the user to switch to the zip or live migration views. In the body, there should be a card containing a table containing the migration history. Currently active or paused migrations should be clickable. When there isn't enough vertical screen space, the body below the top header should scroll along with the card.

![migration-history](https://user-images.githubusercontent.com/82379274/177322218-66dd898d-b677-4d86-aafd-5b0222972633.jpg)
![migration-history-hover](https://user-images.githubusercontent.com/82379274/177322296-13ef8364-5f88-4653-841a-756e0de675d4.jpg)
![migration-history-click](https://user-images.githubusercontent.com/82379274/177322345-95fa1d09-cbf4-48e4-a9ff-fdf4d3288228.jpg)
![migration-history-scroll](https://user-images.githubusercontent.com/82379274/177322367-14202aeb-8de8-4222-bae8-95195c056038.jpg)
![migration-history-dropdown](https://user-images.githubusercontent.com/82379274/177322383-2e12f51a-45e8-44af-98a8-75ee7ec5a216.jpg)

Zip migration:

Should be very similar to the import view. See issue #1139

![migration-zip-migration](https://user-images.githubusercontent.com/82379274/177322783-fd2c7fee-f82f-4984-8094-7da422740181.jpg)
![migration-zip-migration-files](https://user-images.githubusercontent.com/82379274/177322776-0d3668d1-8ee6-4946-9985-2af299ec8887.jpg)
![migration-zip-migration-files-error](https://user-images.githubusercontent.com/82379274/177322767-a1860034-3cea-41f0-ae56-424b80323f18.jpg)
![migration-zip-migration-files-uploading](https://user-images.githubusercontent.com/82379274/177322775-bab19078-66a2-4536-b23c-a234a630d44c.jpg)
![migration-zip-migration-files-uploaded](https://user-images.githubusercontent.com/82379274/177322770-aa39cdef-d800-4ae8-a3c0-c9ba8efe546d.jpg)
![migration-zip-migration-migrating](https://user-images.githubusercontent.com/82379274/177322780-8704ffb1-82e7-4c83-bb2b-5dcbe61ea20b.jpg)
![migration-zip-migration-complete](https://user-images.githubusercontent.com/82379274/177322758-cd6105b6-e5cb-4fbe-8ba4-ca4692437e1b.jpg)
![migration-zip-migration-fail](https://user-images.githubusercontent.com/82379274/177322765-e0b93711-5152-4bb3-a70d-1d874117c780.jpg)

Live migration:

There should be 4 steps with one "hidden" final step. User should be able to navigate forwards and backwards, using both the footer buttons and the main navigation. The user should be able to navigate forward only to the step he has completed, he should not be able to skip steps.

![migration-live-migration-s1](https://user-images.githubusercontent.com/82379274/177323575-182bf607-7940-41e6-b1ba-e28df7b7325f.jpg)

![migration-live-migration-s1-dropdown](https://user-images.githubusercontent.com/82379274/177323559-4a2e6125-b207-41d9-8bb7-1c709061cf2b.jpg)

![migration-live-migration-s1-error](https://user-images.githubusercontent.com/82379274/177323565-7104122f-e323-4f04-8157-45a7296ed027.jpg)

When moving to the next step, there should be a loading sheet, covering the controls until all data is loaded. This applies to all steps.

![migration-live-migration-s2-loading](https://user-images.githubusercontent.com/82379274/177323580-917267cd-64a3-4462-be8b-5a3161422c97.jpg)
![migration-live-migration-s2](https://user-images.githubusercontent.com/82379274/177323586-4df2028c-ad22-45dc-bd1e-1536a200b6b3.jpg)

![migration-live-migration-s3](https://user-images.githubusercontent.com/82379274/177323608-817a8cdf-84af-4ae4-bea9-b657732f76ae.jpg)
![migration-live-migration-s3-ws-create](https://user-images.githubusercontent.com/82379274/177323601-bc45d2dc-4a5d-416e-bf6b-b92b17cd5ce8.jpg)
![migration-live-migration-s3-checkbox](https://user-images.githubusercontent.com/82379274/177323589-8d96e4cb-7e9e-4640-b6a5-c1ab38dddd43.jpg)
![migration-live-migration-s3-multiselect](https://user-images.githubusercontent.com/82379274/177323596-65c58275-b276-4a02-8ac5-6d70660deb1f.jpg)

![migration-live-migration-s4](https://user-images.githubusercontent.com/82379274/177323620-0fb0a500-bada-45c7-aeed-284d32638070.jpg)
![migration-live-migration-s4-collapsed](https://user-images.githubusercontent.com/82379274/177323614-dd89a6b6-3224-4bb0-b589-a5c4eca06fba.jpg)

![migration-live-migration-s5](https://user-images.githubusercontent.com/82379274/177323627-cfd5d3bc-879d-4e4a-aa50-d30c43145a75.jpg)
![migration-live-migration-s5-complete](https://user-images.githubusercontent.com/82379274/177323625-b17e645d-cf8e-4a5d-bd51-25764fdb718a.jpg)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
