### ISSUE TITLE
[UI] Adopt fundamental styles - view Problems

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1147]
### Target
- [ ] Adopt the fundamental styles in Problems view

Use https://github.com/dirigiblelabs/ide-next as reference

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1507

**Comment by StanZGenchev** [comment]
The new view should use the following widgets:

- fd-toolbar
- fd-button
- fd-popover
- fd-input
- fd-toolbar-spacer
- fd-table
- fd-object-status

The search input should have the `style="max-width:30%;"` attribute.
The delete button should delete all records if nothing is selected through its checkbox. If there is one or more records with a checked checkbox, then the delete button should delete only those records.
When a record is added, its default state is "Active". The user should be able to change the status from "Active" to "Solved" or "Ignored". If a record is in a "Solved" state, it can only be switched to "Ignored" and vice-versa. It cannot be set to "Active" again.

Design:

![problems-1](https://user-images.githubusercontent.com/82379274/162024409-936e9e75-077a-4e9a-9b84-bfa6a243603e.jpg)

![problems-2](https://user-images.githubusercontent.com/82379274/162024415-3443604d-2570-47a3-9a06-310c65005edd.jpg)

![problems-3](https://user-images.githubusercontent.com/82379274/162024422-d3db1d1a-9ac2-440b-8c49-f58c1158998f.jpg)

![problems-4](https://user-images.githubusercontent.com/82379274/162024432-1109613d-b90c-4d81-8513-6ba41752f4c4.jpg)

**Comment by StanZGenchev** [comment]
Design change, removing the "Action" column.
At the end of the table there should be an icon button button (sap-icon--expand), that opens a dialog window containing the information about that particular row. By default, the 'Source', 'Creator', 'Created' and 'Program' columns are not shown. Text should wrap and the dialog should be scrollable. The first column, inside the dialog, should have the `style="min-width: 150px"` attribute.

![problems-1](https://user-images.githubusercontent.com/82379274/168638549-aee98d36-8d78-4903-8cb7-0fb26c72fbad.jpg)

![problems-2](https://user-images.githubusercontent.com/82379274/168638557-dd2fbc83-2131-481d-a7ec-03a725f7c4d7.jpg)

![problems-3](https://user-images.githubusercontent.com/82379274/168638558-1a6c1b32-c685-4d9d-ac43-e47477fe2e0e.jpg)

![problems-4](https://user-images.githubusercontent.com/82379274/168638564-6f52c34e-1288-4075-94fe-48c174e91ff9.jpg)

![problems-5](https://user-images.githubusercontent.com/82379274/168639011-7b0a7fec-8adf-42b9-bfc6-6862b59ba61e.jpg)

![problems-6](https://user-images.githubusercontent.com/82379274/168639018-61eb381d-4bbb-4e7f-aa59-7afcd3f32bc1.jpg)

**Comment by StanZGenchev** [comment]
New design after some feedback.
The view should use the following widgets:

- fd-toolbar
- fd-button
- fd-popover
- fd-input
- fd-input-group
- fd-toolbar-spacer
- fd-table
- fd-object-status
- fd-pagination

The search input should be inside its own toolbar, have the `style="max-width:50%;"` attribute and should be shown only when the search button is clicked (button should stay in its selected state while the search toolbar is visible).
The delete button should not delete anything if nothing is selected through its checkbox. If there is one or more records with a checked checkbox, then the delete button should delete only those records.
At the end of the table there should be an icon button (sap-icon--expand), that opens a dialog window containing the information about that particular row. By default, the 'Source', 'Creator', 'Created' and 'Program' columns are not shown. Text should wrap and the dialog should be scrollable. Pagination should show 10 items per page by default. The user should be able to change this to 20, 30 40, 50 and 100.

Design:
![problems-1](https://user-images.githubusercontent.com/82379274/171577951-a7efdec7-2056-4f5b-b90d-aa5a27fe339c.jpg)

![problems-2](https://user-images.githubusercontent.com/82379274/171577964-50bb4852-b623-4e5c-86f0-660360795eb9.jpg)

![problems-3](https://user-images.githubusercontent.com/82379274/171577973-685b7859-ed8e-4b57-afdb-bc2cb0f0b3b4.jpg)

![problems-4](https://user-images.githubusercontent.com/82379274/171577975-0552a301-fec7-4896-8451-1ccd2f624f25.jpg)
