### ISSUE TITLE
[IDE] Debug perspective is not working on Kyma

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#1169]
It seems that in the **deployment.yaml** there is no configuration for service on port **8081** _(used by the debugger)_, also **APIRule**/*VirtualService** for the debugger are not exposed as well.

Related to:
- https://github.com/eclipse/dirigible/issues/1538
- https://github.com/eclipse/dirigible/issues/1539

**Comment by ThuF** [comment]
It seems that the Debug perspective is not working locally as well.
