### ISSUE TITLE
[CI/CD] Testing step in workflow build

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#1173]
For more testing purpose:
1. New pull requests can build images with unique tag to repository
2. Deploy Kyma instance
3. Test XSK
4. Delete everything when is done

**Comment by ThuF** [comment]
It would be great to research how to make use of GitHub Pull Request deployment as described [here](https://sanderknape.com/2020/05/deploy-pull-requests-github-actions-deployments/).

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
