### ISSUE TITLE
[HDBDD] Catalog table type error

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1178]
Error in the `Problems` view `ERROR: No such value available for enum!`

Sample which would cause this error:
```
namespace sap.db;

@Schema: 'ADMIN'

context Products {

    @Catalog.tableType : #GLOBAL_TEMPORARY_COLUMN
    entity Item {
        key ItemId         : String(32);
    	OrderId            : String(500);
    };

};
```
Reference to CDS [annotations](https://help.sap.com/viewer/09b6623836854766b682356393c6c416/2.0.06/en-US/8217aac86d9748d8b034797ecc8065b6.html#)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
