### ISSUE TITLE
[HDBDD] Data type error

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1179]
Error in the `Problems` view `Error at line: 8. No such type found: Double`

Sample which would cause the error: 

```
namespace sap.db;

@Schema: 'ADMIN'

context Products {

    entity Item {
        key ItemId          : Double;
    	OrderId             : String(500);
    };

};
```

Reference to CDS [types](https://help.sap.com/viewer/09b6623836854766b682356393c6c416/2.0.00/en-US/a83fe9b8de1c4f4bbee3eea675851a04.html)

See com/sap/xsk/parser/hdbdd/symbols/SymbolTable.java:56

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
