### ISSUE TITLE
[IDE] Debugger is not working locally

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1180]
The debugger is not loading any `*.xsjs` files for debugging, however `*.js` files can be debugged.

Related to:
- https://github.com/SAP/xsk/issues/1169

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1540

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/commit/497426c165c1171ed83fed90f80f32aad06fb6ca, will be available with the next release of Eclipse Dirigible.

**Comment by ThuF** [comment]
To apply the changes to your XSK instance clone inside the Web IDE the https://github.com/dirigiblelabs/ide-debugger repository and **Publish** the **ide-debugger** project, once imported in the **Workspace**.
