### ISSUE TITLE
Missing destination configuration to be warning

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1197]
### Background
Currently, when deployed to Kyma without destination service binding an exception is thrown - https://github.com/eclipse/dirigible/blob/master/releng/sap-kyma-base/src/main/java/org/eclipse/dirigible/kyma/KymaModule.java#L102 
Destination service is optional dependency and as such not finding the configuration should be a warning and not an exception.

### Target
Change the logger message to warning and continue do not set destination configuration

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1553

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/commit/4d651ee9f293f213ce79d0865b851c77c1cd33b6, will be available with the next release of Eclipse Dirigible.
