### ISSUE TITLE
[HDBDD] @Catalog.tableType #ROW ignored

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1198]
**sample.hdbdd**
```
@Catalog.tableType : #ROW
ENTITY SAMPLE_TABLE {  
    "SAMPLE_FIELD": Integer64;
}
```

the following snippet results in the creation of a column table instead of a row table

**Comment by dpanayotov** [comment]
@LiliyaLazarova can we reuse https://github.com/SAP/xsk/pull/819 here as well?
