### ISSUE TITLE
[CI/CD] Docker image signing within build workflow

### ISSUE THREAD

**Issue by alexkuklin** [SAP/xsk#1204]
Any kind of automatic or semi-automatic deployment to production environment may pose security risks if there's no image verification implemented.

With k8s image verification can be implemented with OPA/Gatekeeper or Connaisseur tools.

We need image signing implemented in pipelines from github side to make it work.

**Comment by krasimirdermendzhiev** [comment]
Related: #1052

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
