### ISSUE TITLE
[Migration] Generate synonym for resources from external schema

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1224]
### Background
There may be projects that define calculationviews on top of tables from schemas which are not defined in the same project.
Example:
```xml
  <DataSource id="someID" type="DATA_BASE_TABLE">
    <viewAttributes allViewAttributes="true"/>
    <columnObject schemaName="external_schema" columnObjectName="EntityTable"/>
  </DataSource>
```
This datasource is external to the project. Namely, `external_schema` and the table `EntityTable` are not defined in the project tree.

### Target
1. Automatically detect if the schema in `columnObject` is defined in the project.
2. If it is - continue current working mode
3. If it is not:
3.1. Change `resourceUri` to be `{SCHEMA_NAME}_{COLUMN_OBJECT_NAME}`
3.2. Create a synonym in the container with this name pointing to the table in the external schema

Same functionality must be available for hdbtablefunctions as well

**Note: Access to the schema and the objects in it must be explicitly _manually_ granted to the XSK user and is out of scope for XSK automation.**

Increased priority as there's a customer for which it's not feasible to manually generate the synonyms.

**Comment by dpanayotov** [comment]
related to
- #390 390

**Comment by vmutafov** [comment]
Fixed with https://github.com/SAP/xsk/pull/1718
