### ISSUE TITLE
[HDBProcedure] Strange Publish/Unpublish Behaviour

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1225]
It seems that if the **Publish** action for a `*.hdbprocedure` fails _(e.g. due to missing table/procedure/dependency)_ and then the required changes are made _(e.g. table/procedure/dependency is created)_ and the `*.hdbprocedure` file is **Unpublished** and **Published** again, the updated HDB Procedure it's not processed at all.

Workaround:

Execute the following query inside the **Database Perspective** for the `local`/`SystemDB` datasource:
```sql
delete from XSK_DATA_STRUCTURES where DS_TYPE = 'HDBPROC' and DS_LOCATION like '%/sample.hdbprocedure'
```

> _**Note**: Where `sample.hdbprocedure` is the procedure that was not processed._

**Comment by ThuF** [comment]
Could be related to:
- https://github.com/SAP/xsk/issues/532

@BorisNen could give more insights if needed.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
