### ISSUE TITLE
[CI/CD] Tomcat remote debugging should be disabled by default

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#1226]
Currently we are starting the XSK tomcat server in debug mode which should not be the case, by default the tomcat server should be started with disabled remote debugging.

**Comment by vmutafov** [comment]
For reference, it's the `jpda` argument here: https://github.com/SAP/xsk/blob/main/releng/server/Dockerfile#L50

Maybe we should use the `developer` Dockerfile for day-to-day development and remove the debugger support as a whole in the customers' Dockerfiles? The Java debugger is not the only one we should have in mind, there is the GraalJS debugger as well.

**Comment by MarinHadzhiev** [comment]
All debuggers should be disabled by default, however there should be a way to enable specific debugger (for example by  providing some env variables) or as Vladi proposed to have a debug version of the image.

**Comment by ThuF** [comment]
@vmutafov, the `developer` image option is fine, but we should be able to “turn on” the remote Java debug mode by an environment variable, so that all XSK related images (including the “runtime only”) should be put into debug mode if needed.

**Comment by ThuF** [comment]
There could be performance implications by the default enabled debug mode:
- https://github.com/SAP/xsk/issues/494

**Comment by dpanayotov** [comment]
### Target
Disable debug in all images
Introduce a new image for which the debug is enabled (check if debug can be enabled via env_var or a new releng directory is needed)
