### ISSUE TITLE
[Migration] Wrong summary message when wrong DB credentials are provided 

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#1230]
Providing wrong DB credentials during migration wizard result in wrong summary message:
<img width="1540" alt="Screenshot 2022-02-08 at 18 40 02" src="https://user-images.githubusercontent.com/57173196/153034153-31f27621-fc4b-4933-b30f-18b68dfef26b.png">

**Steps to reproduce:**
1. open migration perspective
2. provide necessary information till DB user details
3. provide wrong credentials for DB user
4. close error pop-up message
5. click "Finish" button

**Comment by vmutafov** [comment]
@dimitarquanterall could you take a look?

**Comment by dimitarquanterall** [comment]
I will fix it. Please, assign to me

**Comment by ThuF** [comment]
@dimitarquanterall I've assigned the issue to you and set it **In Progress**.

**Comment by dimitarquanterall** [comment]
Seems the most recent version from https://github.com/dirigiblelabs/xsk-ide-migration.git in which the issue is fixed is not merged in XSK.

**Comment by vmutafov** [comment]
@dimitarquanterall it's merged now, could you check again?

**Comment by dimitarquanterall** [comment]
I confirm the merge includes the fix. 
In case or wrong DB credentials the customer is returned back to providing them.

**Comment by ThuF** [comment]
@vmutafov, I'm closing this issue as **resolved**, since @dimitarquanterall confirmed that the fix is included.
