### ISSUE TITLE
[HDBDD] Parser - Entity element not null bug

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1271]
There is an error when the `not null` and `null` specified for entity element are in uppercase. We should allow the parser to accept both lowercase and uppercase.

```
    @Catalog.tableType : #COLUMN
    Entity CONFIGURATION{
        KEY UUID: String(255) NOT NULL;
        COMPANY_ID: String(255) NOT NULL;
        CONFIG: LargeString;
        CONFIG_ID: String(255) NOT NULL;
        LST_UPD_TSTMP: EDate;
        LST_UPD_USR: String(255) NOT NULL;
    };
```
https://github.com/SAP/xsk/blob/main/modules/parsers/parser-hdbdd/src/main/antlr4/com/sap/xsk/parser/hdbdd/core/Cds.g4#L19

**Comment by dpanayotov** [comment]
workaround available - search & replace to lowercase
