### ISSUE TITLE
[HDBDD] Entity element default CURRENT_UTCTIMESTAMP

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1272]
There is an error when `default CURRENT_UTCTIMESTAMP` is specified for an entity element.

```
    @Catalog.tableType : #COLUMN
    Entity talent_sofac_email {
        key SOFAC_EML_ID:	Integer64;
        key RCD_TIMESTAMP: UTCTimestamp default CURRENT_UTCTIMESTAMP;
        MODULE: String(5);
        SO_ID: String(100);
        FAC_ID: String(50);
        TEMPLATE_ID: Integer;
        PERS_MAIL_BDY:    LargeString;
        PERS_SUBJ:	String(4000);
        FLAG: String(20);
        REM_DT: SDate;
        REM_FLAG: String(20);
        CREATE_USER:	String(50);
        UPDATE_USER:	String(50);
        CREATE_DT:	SDate;
        UPDATE_DT:	SDate;
    };
```
Upon doing a simple test in hana the `default CURRENT_UTCTIMESTAMP` seems to be working.

Sql:
<img width="822" alt="Screenshot 2022-02-15 at 11 02 03" src="https://user-images.githubusercontent.com/36267628/154028136-e9914d5b-78af-42d8-aff2-7f0d379dcff8.png">

Table:
<img width="1071" alt="Screenshot 2022-02-15 at 11 01 16" src="https://user-images.githubusercontent.com/36267628/154028225-8ccc4973-4633-43c4-8f2e-6ccd46e9297d.png">

Data:
<img width="865" alt="Screenshot 2022-02-15 at 11 01 21" src="https://user-images.githubusercontent.com/36267628/154028306-eeadfd73-f76d-47ff-b87d-e8fbce71b2c4.png">

**Comment by dpanayotov** [comment]
workaround available - remove default value and execute sql directly to alter table column
