### ISSUE TITLE
[Core] Reconsider the authentication mechanisms in the XSK

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1273]
Currently, when running the XSK locally, following the suggested way in the documentation, we use Form-based authentication provided by Tomcat. This leads to inconsistencies between the dev and production environments where we use OAuth. 

Due to these differences, we have observed several problems:
- websockets are behaving differently on different environments due to different authorization/authentication approaches used
- Tomcat's updates break the existing Form-based authentication but not the OAuth one and this leads to blockers when updating
- difficulties in testing new code that is somehow dependent on the authentication
- maintaining code that does the same thing but in a different way

We should think of a way to use a common authentication mechanism for the environments XSK is running on. This may be Keycloak (or something similar) or at least have an easy way to run XSK locally using the same authentication services as in Kyma/Cloud Foundry, and advise developers to use this approach.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
