### ISSUE TITLE
[Parser] Use the HanaVisitor for parsing hdbtablefunction artifacts

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1276]
Currently, parsing `hdbtablefunction`s is done using string operations. This leads to problems when there are comments in the SQL code or other statements we did not consider. Also, we should be able to parse the `schema` and `name` properties as they are needed for generating synonyms.

We should use a proper parser (e.g. the `HanaVisitor`) as it would be easier to parse the function's `schema` and `name`.

**Comment by ThuF** [comment]
@vmutafov I guess we should do the same for `*.hdbprocedure` files, as they also cause some issues recently:
- https://github.com/SAP/xsk/issues/1222
- https://github.com/SAP/xsk/issues/1118

**Comment by vmutafov** [comment]
@ThuF Hmm, I'm not sure about them. I'd have to take a look.

**Comment by vmutafov** [comment]
@Fluctuationqt could you provide a sample `hdbtablefunction` for which you hit this issue?

**Comment by Fluctuationqt** [comment]
```
FUNCTION "_SYS_BIC"."customer_sample::SAMPLE_FUNCTION" (CurrentUserId INTEGER)
RETURNS TABLE ("count" INT,  "ADDRESS" DECIMAL(18,0))
LANGUAGE SQLSCRIPT
SQL SECURITY DEFINER
  AS 

 
 /********* Begin Procedure Script ************/ 
 BEGIN 
 	 var_out = SELECT
		 *
	FROM "_SYS_BIC"."customer_sample.VIEWS/SALES_ORDERS";


return :var_out;
END;
```

This sample, parsed by XSKHDBTableFunctionParser, results in a model with name equal to ""_SYS_BIC"."customer_sample::SAMPLE_FUNCTION"".
The proper expected output should be a model with name "customer_sample::SAMPLE_FUNCTION" and schema "_SYS_BIC".

**Comment by dpanayotov** [comment]
high priority as dependency for customer issue
