### ISSUE TITLE
[Parser] Update the hdbtabletype parser to recognize the artifact's schema

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1277]
Currently, the resulting model of parsing `hdbtabletype`s does not have a schema set. This is necessary for the synonyms generation during a migration.

**Comment by vmutafov** [comment]
@Fluctuationqt could you provide a sample `hdbtabletype` for which you hit this issue?

**Comment by Fluctuationqt** [comment]
```
TYPE “XSK_SAMPLES_HDI_CUBE”.“customer_sample::publishers” AS TABLE (
   “PUBLISHER” INTEGER,
   “NAME” NVARCHAR(50),
   “PRICE” DECIMAL,
   “COUNT” INTEGER
)
```
This sample, parsed by XSKTableTypeParser, results in a model with schema equal to null.

**Comment by dpanayotov** [comment]
high priority as dependency for customer issue
