### ISSUE TITLE
[Parser] Reconsider the parser results' object types

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1278]
Currently, all parsers return an object where its class inherits `XSKDataStructureModel`. This hierarchy may lead to problems as, for example, some Hana artifacts don't have a name. We should maybe rethink the inheritance chain of the parser results as it leads to wrong assumptions about the parsing results. Also, this would remove the need for casting the base type to concrete types at some places in the code.

**Comment by dpanayotov** [comment]
high priority as dependency for customer issue

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
