### ISSUE TITLE
[Core] Dependencies between artifacts not considered during deployment

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1283]
When an artifact depends on another one they should be deployed in the correct order

**Comment by ThuF** [comment]
Related to:
- https://github.com/eclipse/dirigible/issues/1578
- https://github.com/eclipse/dirigible/commit/9fb7486f6199894395beab78ef1e8d06e968b10a
- https://github.com/eclipse/dirigible/commit/6a5cb319277fc99a65a7b2fad0db0cbed28e5774

**Comment by dpanayotov** [comment]
to be fixed with #1304
