### ISSUE TITLE
[API] $.hdb loadProcedure method missing

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1289]
`loadProcedure()` method of the `$.hdb` api is used in a customer project and should be implemented.

https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.hdb.Connection.html

**Comment by ThuF** [comment]
Reference sample in Eclipse Dirigible:
- https://www.dirigible.io/samples/basic/database-procedure-call/
