### ISSUE TITLE
[Research] Build alpine image with tomcat

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#1293]
Build alpine image with tomcat

Goal:

1. Build base image and verify that XSK is working with it.
2. Run protecode scan

**Comment by alexkuklin** [comment]
Done: https://github.com/alexkuklin/xsk/commit/794d3ea4a47c8969c9d2439df9828f32c489f82f

**Comment by krasimirdermendzhiev** [comment]
At this point SAP machine is not supporting Alpine. We are stay on distroless image.
