### ISSUE TITLE
[Infrastructure] Make use of SapMachine

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#131]
Make use of SapMachine wherever is applicable (base images, CI/CD, ...)

**Comment by ThuF** [comment]
SapMachine Docker Image: https://hub.docker.com/_/sapmachine

**Comment by dspenchev** [comment]
The integration of SapMachine JDK with the GitHub action `setup-java` is [underway| https://github.com/actions/setup-java/issues/72]. Till then only way to add the JDK distro is by using a local file. More information could be found [here](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Installing-Java-from-local-file).

**Comment by ThuF** [comment]
![Screenshot 2021-04-29 at 13 42 50](https://user-images.githubusercontent.com/4092083/116539037-fcb0e180-a8f0-11eb-9efc-e221342be9dd.png)

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/200
