### ISSUE TITLE
Incorrect handling of string filter attributes in odata

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1325]
A filter like this results in inproper handling in case the requested field is of type string. As the provided value is assignable to an int
services.xsodata/MaterialInfo?$filter=VTWEG%20eq%20%2700%27)

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1631

**Comment by dpanayotov** [comment]
fixed with https://github.com/eclipse/dirigible/pull/1632
