### ISSUE TITLE
Truncate SYNCHRONIZER_ARTEFACT_MESSAGE  

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1326]
Column SYNCHRONIZER_ARTEFACT_MESSAGE  in DIRIGIBLE_SYNCHRONIZER_STATE_ARTEFACTS is not long enough for some of the artifacts.

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1633

**Comment by dpanayotov** [comment]
To be resolved by truncating the artifact body and not trying to put the whole message in the database

**Comment by ThuF** [comment]
Will be available with the next release of Eclipse Dirigible
