### ISSUE TITLE
Request parameters not set correctly when calling destination

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1329]
### Details
When setting request parameters for making a call to a destination the parameters are put properly in the URL

### Example
https://github.com/SAP/xsk/blob/products-sample-next/samples/products/xsjob/sync.xsjs#L139
```js
var destination = http.readDestination("products.xsjob", "products");
var client = new http.Client();
var request = new http.Request(http.GET, "/Orders");
request.parameters.set("$expand", "Customer,Order_Details($expand=Product($expand=Category))");
request.parameters.set("$skiptoken", param.skiptoken);
client.request(request, destination);
```

**Comment by dimitarquanterall** [comment]
Can you, please, check again or provide more details about reproducing the problem. Tests show parameters are correctly set.

**Comment by dpanayotov** [comment]
cannot reproduce anymore
