### ISSUE TITLE
[XSOData] CUD using param undefined

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1332]
**Details**
When there is Create, Update, Delete using in XSOData point to an xsjs function, the function param is undefined

**Comment by MarinHadzhiev** [comment]
At the moment, no parameter is passed to the event handler function (as you can see in onEvent.xsjs). We need to pass a parameter to the handler function which contains - connection, afterTableName, beforeTableName according to the event type as documented [here](https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/68c5a3bca9294e4098454dccbc73f7a9.html). 

To be able to do this, we need to create a local temporary table ([documentation](https://help.sap.com/viewer/c1d3f60099654ecfb3fe36ac93c121bb/2021_4_QRC/en-US/20d58a5f75191014b2fe92141b7df228.html)) and insert into it the record that will be updated/deleted/created.

The magic with OData events handling is happening in **AbstractSQLProcessor**. Also keep in mind that this is in the Dirigible and it is not working only with HANA.

Contact me for more details and help.

**Comment by MarinHadzhiev** [comment]
Example SQL for creating temporary table based on calculation view in HANA

`CREATE LOCAL TEMPORARY TABLE #MY_TEMP_TABLE AS (SELECT * FROM "sample-hdi::SIMPLE_CALC_VIEW") WITH NO DATA;`

**Comment by ThuF** [comment]
PRs:
- https://github.com/eclipse/dirigible/pull/1721
- https://github.com/SAP/xsk/pull/1558
