### ISSUE TITLE
[Engines] Explore the capabilities of testsconteiners library

### ISSUE THREAD

**Issue by GrozevJunior** [SAP/xsk#135]
Testcontainers is a Java library that supports JUnit tests, providing lightweight, throwaway instances of common databases, Selenium web browsers, or anything else that can run in a Docker container.

It could be quite useful for testing our DB access layer.

**Comment by GrozevJunior** [comment]
Link to the library https://www.testcontainers.org/

**Comment by BorisNen** [comment]
Fixed with https://github.com/BorisNen/xsk/commit/2385970b868d02f464766e9fab056fea4cfdf0d5
