### ISSUE TITLE
[Core] Bearer authorization header is not recognized

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1354]
Sending the `Bearer` authorization header with lowercase _(e.g. `bearer exy123x...`)_ is not considered as valid authorization header:
- `Bearer exy123x...` - recognized
- `bearer exy123x...` - not recognized

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1642

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/commit/147896dd66642abc01863688228bca317bde1b4c, will be available with the next release of Eclipse Dirigible.
