### ISSUE TITLE
Issue with handling big decimal in prepare statement

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1368]
Example 
var st4 = conn.prepareStatement(...);
st4.setDecimal(1, parseFloat(7));

results in the following exception
Something went wrong creating the Price Request. Error: TypeError: invokeMember (setBigDecimal) on org.apache.commons.dbcp2.DelegatingPreparedStatement@247a404c failed due to: Cannot convert '7'(language: Java, type: java.lang.Integer) to Java type 'java.math.BigDecimal': Unsupported target type.
        at <js> Module.loadScript(Unnamed:228:6272-6279)
        at <js> Module.load(Unnamed:203:5448-5472)
        at <js> :program(Unnamed:1:0-31)
        at org.graalvm.polyglot.Context.eval(Context.java:425)

**Comment by delchev** [comment]
Fixed with: https://github.com/SAP/xsk/commit/41cd4b098208404b232fa64b6a0dc6428f3aaceb
