### ISSUE TITLE
Improve problems message for hdi failure

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1383]
### Background
Currently failure to create the hdi container always logs the same 2 problems in the problems view
1. Could not create the container "NAME"
2. SAP DBTech JDBC: [362]: invalid schema name: NAME#DI: line 1 col 6 (at pos 5) 

This is not helpful and does not show the actual reason for the failure 

### Target
Add the actual problem that caused the failure to create HDI container to the problems view

**Comment by dimitarquanterall** [comment]
Please, assign to me
