### ISSUE TITLE
[Tests] Add tests for the replacement of SESSION_USER with SESISON_CONTEXT('APPLICATIONUSER')

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1395]
Currently, we don't seem to have tests asserting if `SESISON_CONTEXT('APPLICATIONUSER')` works on HANA databases. We have some xsjs files in the `integration-tests/ui` module but they don't seem to be run.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
