### ISSUE TITLE
[Branding] Update the welcome page

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#140]
Replace the default `Welcome to Eclipse Dirigible` page with XSK specific one:

![Screenshot 2021-04-07 at 10 29 28](https://user-images.githubusercontent.com/4092083/113828074-ab4b8180-978c-11eb-86ab-ff945afdc660.png)

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/133

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
