### ISSUE TITLE
[API] Procedures - Support for nullable values

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1415]
Add handling for `null` procedure values.

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1652

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/commit/fb4e9ead9b30e65d44513baf51b0153ec9b75b37, will be available with the next release of Eclipse Dirigible.
