### ISSUE TITLE
[Migration] Add parallel processing of migrated files

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1419]
Currently, we make several modifications to HANA artifacts when migrating a project. Those modifications are happening one after the other in a sequential way. 

We should try to perform those modifications in a parallel way in order to make them faster. We should be cautious about modifications that may be dependent on some other.

Related to:
- https://github.com/SAP/xsk/issues/1210

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
