### ISSUE TITLE
[API] Destination - Missing Properties

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1430]
```javascript
const destination = $.net.http.readDestination('', 'desname');
$.trace.error("HOST: "+destination.host);
$.trace.error("PATH: "+destination.pathPrefix);
```

should return the corresponding values, while they are returning `undefined` now.

All properties of a destination should be available for the destination object even the customer properties. Note that in BTP destination the `pathPrefix` is part of the URL

**Comment by dpanayotov** [comment]
Implementation proposal is to wrap the cloud-sdk's Destination object in our own object (in Java) which exposes only the necessary properties and methods.
