### ISSUE TITLE
[Documentation] Create an XSK Documentation homepage

### ISSUE THREAD

**Issue by slavipande** [SAP/xsk#1480]
Currently, there's no XSK Documentation page. We've discussed it'd be good to have one that links to existing and planned documentation sections. 

Here's an exemplary design prepared by a UX colleague:
![2022-03-18_10-23-15](https://user-images.githubusercontent.com/46915717/159959599-4ad13bff-2f23-4386-9ace-a67ee7a508c1.png)

In addition, we have to:

- Add three more tiles to the proposed design of the XSK docs homepage - Concepts, Architecture, Features
- Change order of tiles, so community and faq are the last two
- Compare and decide - should we have **Setup** or **Get Started** as the first tile, top left

Best regards,
Svetoslav

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
