### ISSUE TITLE
[IDE] Save button in extension editor doesn't work

### ISSUE THREAD

**Issue by ivanvolkoff** [SAP/xsk#1489]
In extension form-based editor save button doesn't work.

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1679

**Comment by dimitarquanterall** [comment]
It seems to be working according to my tests. Can you describe exact steps to reproduce the problem?

**Comment by ivanvolkoff** [comment]
The problem was in my setup.
