### ISSUE TITLE
Clear all POMs of unused dependencies

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#1491]
Almost all of the POM files contains unused dependencies which should be removed

For example see engines-hdbti - https://github.com/SAP/xsk/blob/main/modules/engines/engine-hdbti/pom.xml 
It contains some dependencies that might not be needed (ie websockets, bpm, graalvm)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
