### ISSUE TITLE
[Research] Kyma - Istio

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#150]
Research the [Istio](https://istio.io/) component and potential usage in [Kyma](https://kyma-project.io/).

Components:
- Istio
- Istio-Ingress-Gateway
- Istio-Proxy

**Comment by krasimirdermendzhiev** [comment]
![Istio-Istio](https://user-images.githubusercontent.com/82384876/115258534-bd88d080-a139-11eb-8f3b-f56cd19d89f4.png)
![Istio-Istio Architecture](https://user-images.githubusercontent.com/82384876/115258545-bf529400-a139-11eb-8211-051cff6a9fb0.png)

**Comment by krasimirdermendzhiev** [comment]
Clusters
![Istio-Clusters](https://user-images.githubusercontent.com/82384876/115355555-734c3180-a1c3-11eb-97c7-ea8ff9aac3b6.png)

**Comment by krasimirdermendzhiev** [comment]
Network Models
![Istio-Network Models](https://user-images.githubusercontent.com/82384876/115355782-ab537480-a1c3-11eb-91c4-006340c220c4.png)

**Comment by krasimirdermendzhiev** [comment]
Control Plane Models

![Istio-Control Plane](https://user-images.githubusercontent.com/82384876/115355917-cfaf5100-a1c3-11eb-8d31-739ed534561f.png)

**Comment by krasimirdermendzhiev** [comment]
Trust Models

![Istio-Trust Models](https://user-images.githubusercontent.com/82384876/115356056-f4a3c400-a1c3-11eb-8c01-b59e56d2c4e1.png)

**Comment by krasimirdermendzhiev** [comment]
Mesh Models

![Istio-Mesh models](https://user-images.githubusercontent.com/82384876/115356335-392f5f80-a1c4-11eb-8780-daa29aab4b78.png)

**Comment by krasimirdermendzhiev** [comment]
Endpoint Discovery

![Istio-Endpoint Discovery](https://user-images.githubusercontent.com/82384876/115356671-8c091700-a1c4-11eb-9554-4c56bb4b6293.png)

**Comment by krasimirdermendzhiev** [comment]
Namespace  tenancy

![Istio-Namespace tenancy](https://user-images.githubusercontent.com/82384876/115356800-ae029980-a1c4-11eb-833c-13c9d2497581.png)
