### ISSUE TITLE
[Research] Kyma - Jaeger

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#151]
Research the [Jaeger](https://www.jaegertracing.io/) component and potential usage in [Kyma](https://kyma-project.io/).

Components:
- Jaeger
- Jaeger-Operator

**Comment by krasimirdermendzhiev** [comment]
![istio-Jaeger (2)](https://user-images.githubusercontent.com/82384876/115259204-57e91400-a13a-11eb-97b8-0034f29e9b9e.png)

**Comment by ThuF** [comment]
Research completed.
