### ISSUE TITLE
[Migration] DU with multiple projects generates multiple HDI containers

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1527]
### Background
When there's a DU with multiple packages in HANA, each package is converted to a project in XSK. Then each project gets its own `.hdi` file and will be deployed in separate HDI container. There may be calculationviews from package1 which are using calculationviews from package2 which results in inter-container access with which there is a need to resolve the permissions issue.

### Target
TBD: should actually one 1 hdi file be generated as it'll represent 1 container? Currently, we'll get multiple containers and additional synonyms will be needed.

**Comment by Fluctuationqt** [comment]
This issue is duplicate with https://github.com/SAP/xsk/issues/1595

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
