### ISSUE TITLE
[Research] Kyma - Docker Registry

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#154]
Research the Docker Registry component and potential usage in [Kyma](http://kyma-project.io/).

Components:
- Docker-Registry

**Comment by StanZGenchev** [comment]
Kyma does not have a build-in container registry. Therefore we have to take an existing one and integrate it, or build our own from scratch.
We looked into 3 popular options.

1 - Quay
2 - Harbor
3 - Docker Distribution/Registry

Quay is the most feature rich option but has some oddities to it. You have to have a RedHat account if you do not want to build it from source every time there is a new release, it is designed to integrate with other RedHat products like OpenShift and is generally more inflexible if you want customization. It's a good option if you already use other RedHat products or you need all the advanced features like the build system.

Harbor is slightly behind on features. The biggest difference being, that Quay has a build system while Harbor does not. Harbor however, is more popular and more general-purpose oriented. It has more customization options and is more easily deployed and managed even if you are using bare-bones Kubernetes. It's a good solution if you are looking to extend an existing system and you do not want a huge maintenance burden.

Docker Registry is the bare-bones solution. It does not have a front-end, no fancy features like OpenID Connect, Helm charts, LDAP and image squashing. It's most often used as a base for building a custom container registry. In fact, Harbor is based on this. It's a good solution if you want/need to build your own authentication, front-end and build system or if you already have a system that handles those things and you just need a simple container registry.

Considering our needs, I think Harbor will be a nice fit.
