### ISSUE TITLE
[Migration] Transform attributes in calculation views

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1540]
### Target
1. Transform the `associatedObjectUri` to point to a synonym. See example how it looked before [here](https://github.com/SAP-samples/hana-structurer-one/blob/main/Models/SAP_CA_TWEETB.calculationview#L76). This would mean from `/Summit15.Models/calculationviews/SAP_DIM_TWEETINFOB` to `Summit15.Models:: SAP_DIM_TWEETINFOB`
2. Transform the `measureMapping` to omit the schema name.  See example [here](https://github.com/SAP-samples/hana-structurer-one/blob/main/Models/SAP_AN_TWEET.analyticview#L43) even though that's analytics view. The `schemaName` must be removed

**Comment by dimitarquanterall** [comment]
Please, assign to me.
