### ISSUE TITLE
[Migration] Store the state of the migration in the frontend

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1546]
As observed with bigger projects, their migration could take a lot of time. We should be able to "close" the migration perspective and return to it at a later point in time. This could be achieved by extending the performed migrations list on the first page of the migrations perspective so as to be able to navigate to migrations that are still not done. In order to support this behavior, the frontend should be able to get and process the state of the internal Flowable process used in the backend.

**Comment by tdermendjiev** [comment]
Implemented by https://github.com/dirigiblelabs/xsk-ide-migration/pull/75

**Comment by dpanayotov** [comment]
fixed with https://github.com/dirigiblelabs/xsk-ide-migration/pull/75
