### ISSUE TITLE
[Migration] Remove internal MacOS folders from imported ZIPs

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1548]
As observed on several MacOS machines, ZIPs imported into the migration perspective contain an internal MacOS folder that in some projects results in a slowdown of the whole migration as its files are being processed. We should strip the MacOS folder in Dirigible's `TransportRestService`.

**Comment by ivanvolkoff** [comment]
Closed in https://github.com/eclipse/dirigible/pull/1726
