### ISSUE TITLE
[Core] Split constants files

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1575]
As there are quite a few files declaring constants, we should change this to have the constants split into more meaningful classes instead of a `Constants` class declaring various constants for different functionalities. For example, we may have a class `XSFileExtensions` declaring constants about file extensions and similar other more granular classes. We should have in mind that some constants should only be declared where used if used only in one place.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
