### ISSUE TITLE
[UI] Leave only necessary views

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1593]
### Details
Currently XSK is shipped with the dirigible UI which packages a lot of perspectives and views which are not relevant to the XSK scenario and may cause confusion (and possibly issues) if users begin clicking around.

### Target
Disable the views and perspectives which are not part of the migration journey:
#### Perspectives
1. Documents perspective
2. Operations perspective
3. Terminal perspective
4. Repository perspective (TBD)
5. Debugger perspective (TBD)

#### Views
1. Access
2. Constraints (now it's visible in `show view` menu but nothing happens when pressed)
3. DataStructures
4. Documents
5. Extensions
6. History
7. Jobs
8. Listeners
9. Logs
10. Plugins
11. Properties
12. Registry
13. Roles
14. Snapshot
15. Websockets

**Comment by dimitarquanterall** [comment]
Tests can be made by switching to "server lite" branch: https://github.com/SAP/xsk/tree/server-lite and using the deploy from server-lite folder.
