### ISSUE TITLE
[IDE] When multiple files with same name are opened in tabs, project name should be shown in the tab's title

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#1596]
When two files with the same name are opened, the titles in the editor's tab bar only show their name and it's difficult to distinguish which file comes from what project/folder.
Show the path in the tab titles of files with the same name, when we have such files opened in the editor.

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1743

**Comment by StanZGenchev** [comment]
Fixed in new layout

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
