### ISSUE TITLE
[Migration] hdiconfig file to not have a name

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1609]
### Details
SAP tools processing HDI artifacts are looking for `.hdiconfig` file but XSK generates such file with name `<project>.hdiconfig`

### Target
Remove the name of the hdiconfig file and leave it without a name so it becomes just `.hdiconfig`

**Comment by vmutafov** [comment]
Fixed with https://github.com/SAP/xsk/pull/1740
