### ISSUE TITLE
[Migration] modifyProjectFiles() called multiple times over the same file

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#1614]
While debugging i noticed [xskProjectModifier::modifyProjectFiles(List<IFile>)](https://github.com/SAP/xsk/blob/5bf28da83834d30fff66ceb0c3b5c53f9e510c79/modules/engines/engine-core/src/main/java/com/sap/xsk/modificators/XSKProjectFilesModificator.java#L55) iterates over the same project files multiple times. This may slow down the calcuating changes step.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
