### ISSUE TITLE
Restructure POM files for docker images and buildpacks to adopt inheritance for better code management

### ISSUE THREAD

**Issue by alexkuklin** [SAP/xsk#1644]
### Target

Change a way POM's are organized so changes to base components configuration could be made at one place, without need to copy-paste them to all POM files.

i.e., sap-cf and sap-kyma have almost no difference:
```
< 	<name>XSK - Releng - Cloud Foundry</name>
< 	<artifactId>xsk-releng-cf</artifactId>
---
> 	<name>XSK - Releng - Kyma</name>
> 	<artifactId>xsk-releng-kyma</artifactId>
97c97
< 		<!-- Cloud Foundry - Base -->
---
> 		<!-- Kyma - Base -->
100c100
< 			<artifactId>dirigible-sap-cf-base</artifactId>
---
> 			<artifactId>dirigible-sap-kyma-base</artifactId>
```
so it should be restrictured to sap version as parent and sap-cf and sap-kyma as subverstions of sap.

Other notes on the matter a placed in #1498 comments.

**Comment by krasimirdermendzhiev** [comment]
Test the image on kyma.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
