### ISSUE TITLE
[HDBDD] Remove support for entity names that include the schema in views

### ISSUE THREAD

**Issue by d-velev** [SAP/xsk#1660]
Currently, it is possible do define a view like so:
```     
define view employees_view_basic as
        select from "itest::EmployeesWithViewDefinitions.employees" as EMP
        {
            "EMP"."ID" as "EmployeeID",
            "EMP"."NAME" as "EmployeeName",
            "EMP"."ADDRESS" as "EmployeeAddress",
            "EMP"."AGE" as "EmployeeAge",
            "EMP"."PHONE" as "EmployeePhone"
        };
```
where the reference to the entity in the select statement also includes the schema prepended with a `::` delimiter. Doing this in Neo results in the following error:  `Paths with namespace are not allowed inside view definitions`.

**Comment by dpanayotov** [comment]
should have not impact for migrated applications - the syntax was not supported before and there should be no occurrences in migrated applications. may be addressed later

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
