### ISSUE TITLE
[Parsers] getting rid of setters

### ISSUE THREAD

**Issue by ivanvolkoff** [SAP/xsk#1664]
Due to implementing builder patterns in [XSKDataStructureModel](https://github.com/SAP/xsk/blob/main/modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/model/XSKDataStructureModel.java#:~:text=public%20class-,XSKDataStructureModel,-%7B) the old setter methods should be removed and instances should be instantiated in  "a new way". Using setters may lead to incorrectly initialized objects. Also, it's a better practice to have immutable objects (no setters).

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
