### ISSUE TITLE
[Migration] Javascript parse errors are swallowed

### ISSUE THREAD

**Issue by tdermendjiev** [SAP/xsk#1665]
No error is thrown if javascript file is not parsed successfully during migration. 

Steps to reproduce:
1. Add any syntax error (e.g. remove a bracket) in `migration-service.mjs` and save
2. Start zip migration
3. After a few seconds the message `Successfully migrated uploaded Delivery Unit(s)! Go to workspace "workspace" and publish them.` appears but the migration status is still `MIGRATION_STARTING`.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
