### ISSUE TITLE
[OData] null handling in filter

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1669]
Example of filters 
 Apps?$filter=DomainId%20ne%20null
 Apps?$filter=DomainId%20eq%20null

do not result in the correct SQL - "IS NOT NULL" & "IS NULL"

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1781

**Comment by MarinHadzhiev** [comment]
fixed with https://github.com/eclipse/dirigible/pull/1782

**Comment by MarinHadzhiev** [comment]
fixed with version 0.16.2
