### ISSUE TITLE
[Migration] Ignore files and directories

### ISSUE THREAD

**Issue by tdermendjiev** [SAP/xsk#1673]
In certain scenarios not all of the project files need to pass through the entire migration logic and there should be a way to ignore them. For example, the project may contain SAP UI5 SDK which is 500+ MB. This would slower the migration significantly (~1hr) while unnecessary. The user should be able to add a list of files and directories to be copy-pasted into the project without being iterated by the migration tool.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
