### ISSUE TITLE
[OData] Original exception from odata handlers is not visible in the response

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1679]
Currently if an exception is thrown within an odata handler it is not visible in the response.
You can simulate this by haveing a xsjslib function that just throws an excpetion e.g. throw "Some error msg";
 The response from the call should look like this
`{
	"error": {
		"code": "",
		"message": {
			"lang": "en-US",
			"value": "Some error msg"
		}
	}
}`

**Comment by dpanayotov** [comment]
Original exception message not propagated upwards, but only last message is returned as message as specified [here](https://github.com/eclipse/dirigible/blob/master/modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java#L346). Original exception message is wrapped [here](https://github.com/eclipse/dirigible/blob/master/modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/handler/ScriptingOData2EventHandler.java#L131)

Exceptions for all handlers (before/after/on-create/update/delete) should be adjusted to show the exception from the xsjs execution

**Comment by dpanayotov** [comment]
fixed with https://github.com/eclipse/dirigible/pull/1800
