### ISSUE TITLE
[Parsers] Implement Integration Tests for hdbview

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#168]

**Comment by Wildflowerr** [comment]
Depends on https://github.com/eclipse/dirigible/pull/860 to be merged and released afterwards.

**Comment by Wildflowerr** [comment]
Fixed with https://github.com/SAP/xsk/pull/199/commits/7a43b03ff5aa48ac0e408ef3acab7fd9bfcaa61a

**Comment by ThuF** [comment]
Release `5.10.3` is scheduled: https://github.com/eclipse/dirigible/actions/runs/839087258

**Comment by ThuF** [comment]
Eclipse Dirigible 5.10.3 was released: https://github.com/eclipse/dirigible/releases/tag/v5.10.3
