### ISSUE TITLE
[Tests] Try to run PR Selenium tests for Migration with a KYMA deployment 

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#1695]
This issue should be addressed after https://github.com/SAP/xsk/issues/1694.

1. Replace the locally built&executed (from the PR branch) XSK with a Kyma deployment against which the selenium tests should execute.
2. Check for any flakiness related to the KYMA deployment

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
