### ISSUE TITLE
[Tests] Migration Selenium tests - Improve test project

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#1696]
1. Research and note all of the current DU transformations made during the migration procedure.
2. Find a way to sample project that would test all of the transformations.
3. This project should be deployed on HANA 2 and also we must have the expected content after migration, such that the expected content would be a working and deployable HANA Cloud project.
4. Add random non-transformed files to the sample project to validate that they also are migrated properly.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
