### ISSUE TITLE
[API] $.request.parameters is empty on POST with form-data

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1698]
### Details
When sending a POST request with form-data to an XSJS service the $.request.parameters entity is empty. It seems that `$.request.parameters` takes only the query parameters and not the ones from the body.

When sending a POST request with `x-www-form-urlencoded` the kv-pairs are not available anywhere in the $.request object

### Expected
`$.request.parameters` must have the query parameters and the body as well.

### Steps to reproduce
1. Prepare a service.xsjs with the body `$.trace.error(JSON.stringify($.request));`
2. Send a POST request from postman with a body form-data (same with x-www-form-urlencoded)
3. See that the body is in the `.entities[index].parameters`, but not in the `.parameters`

$.request.entities to obtain data also from PUT and PATCH

**Comment by Fluctuationqt** [comment]
The following documentation i found [here](https://stackoverflow.com/questions/5964122/jax-rs-with-jersey-passing-form-parameters-to-put-method-for-updating-a-resourc) was useful to me.
Seems like applying the last one of the listed conditions resolved this issue. 


## Java™ Servlet Specification (Version 2.3), Chapter 4.1:
> Request parameters are strings sent by the client to a servlet container as part of a request.
When the request is a HttpServletRequest, the attributes are populated from the URI
query string and possibly posted form data. The parameters are stored by the servlet
container as a set of name-value pairs. Multiple parameter values can exist for any given
parameter name. The following methods of the ServletRequest interface are available
to access parameters:
• getParameter
• getParameterNames
• getParameterValues

> The getParameterValues method returns an array of String objects containing all
the parameter values associated with a parameter name. The value returned from the
getParameter method must always equal the first value in the array of String objects
returned by getParameterValues.
All form data from both the query string and the post body are aggregated into the request
parameter set. The order of this aggregation is that query string data takes precedence over
post body parameter data. For example, if a request is made with a query string of a=hello
and a post body of a=goodbye&a=world, the resulting parameter set would be ordered
a=(hello, goodbye, world).
Posted form data is only read from the input stream of the request and used to populate the
parameter set when all of the following conditions are met:

> 1. The request is an HTTP or HTTPS request.
> 2. The HTTP method is POST
> 3. The content type is application/x-www-form-urlencoded
> 4. The servlet calls any of the getParameter family of methods on the request object.
> If any of the getParameter family of methods is not called, or not all of the above
conditions are met, the post data must remain available for the servlet to read via the
request’s input stream.

**Comment by vmutafov** [comment]
Fixed with https://github.com/SAP/xsk/pull/1720
