### ISSUE TITLE
[Tests] XSOData with XSJS handlers

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1711]
### Target
Implement an application test that has the following functionality
1. Has an hdbdd with at least 1 entity
2. Has an xsjs with create/update/delete handlers
3. Has an xsodata which exposes the entity and uses the xsjs as CUD handler

The test should do the following:
1. Execute create, update, delete request against the odata
2. After each request validate that the changes are reflected in the database (ie through querying the odata)

**Comment by vmutafov** [comment]
Fixed with https://github.com/SAP/xsk/pull/1794
