### ISSUE TITLE
[CORE] Error logged on saving file 

### ISSUE THREAD

**Issue by dimitarquanterall** [SAP/xsk#1717]
On file save the following errors are logged: 
`[ERROR] [http-nio-8080-exec-7] o.e.d.e.a.s.ScriptEngineExecutorsManager - Script Module [/ide-entity/template/transformer-on-save] does not exist, hence cannot be processed`
`[ERROR] [http-nio-8080-exec-7] o.e.d.e.a.s.ScriptEngineExecutorsManager - Script Module [/template-form-builder-angularjs/template/generator-on-save] does not exist, hence cannot be processed`

**To Reproduce**
1. Download and build latest XSK. 
2. Deploy in Tomcat.
3. Open the Workbench and create / import a project. 
4. Create New -> File.
5. Open the new file and add content. 
6. Save and see errors in terminal. 

**Environment**
 - OS: Mac OS X
 - Server: Apache Tomcat/8.5.73
 - Java: openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
