### ISSUE TITLE
JS doesn't seem to be executed until Preview tab is loaded at least once

### ISSUE THREAD

**Issue by dimitarquanterall** [SAP/xsk#1722]
**Describe the bug**
It seems javascript files in Workbench perspective are not executed on save / publish if the Preview view have not been displayed at least once.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a fresh XSK in Tomcat.
2. Import / create a project.
3. Add a simple JS file to the project. For example: 
`console.log('====================== Test log');`
`console.warn('====================== Test warning');`
`console.error('====================== Test error');` 
4. Save and / or publish the sample file.
5. See that events don't display neither in Console view, nor in terminal. 
6. Click on Preview button to display it.
7. Click back on Console button to display the console.
8. Save the sample file again.
9. Events now start logging in console, as well as in terminal.

**Expected behaviour**
JS files are being executed on save / publish without the need to switch to Preview. 

**Desktop**
 - MacOS
 - XSK run in Tomcat

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
