### ISSUE TITLE
[API] HDB data types mapping to JavaScript ArrayBuffer Type

### ISSUE THREAD

**Issue by ivanvolkoff** [SAP/xsk#1736]
Implement the data type conversion as stated by the [SAP documentation](https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.hdb.html) for hdb types that should be converted to ```ArrayBuffer``` type.

Mapping in [hdbUtils.js](https://github.com/SAP/xsk/blob/main/modules/api/api-xsjs/src/main/resources/META-INF/dirigible/xsk/hdb/hdbUtils.js)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
