### ISSUE TITLE
[Migration] Move xsk-ide-migration module inside main repository

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1738]
Currently, the source code of the migrations UI and backend is in `dirigiblelabs/xsk-ide-migration` and is merged into `SAP/xsk` using the `-Pcontent` build flag. We should move the migrations source into the `SAP/xsk` repository similar to how other Dirigible modules were moved inside the main Dirigible repository in order to have easier maintenance

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
