### ISSUE TITLE
[API] $.security.crypto methods should return a JS ArrayBuffer

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#1745]
Currently, the `crypto` API returns Java `byte[]` into the JS world. As stated in the docs (https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.security.crypto.html), it should return a JS ArrayBuffer.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
