### ISSUE TITLE
[Xsodata] Xsjs event handlers are not working

### ISSUE THREAD

**Issue by aihanrashidov** [SAP/xsk#1753]
Xsodata xsjs event handlers are not working and resulting in an error:

<img width="803" alt="Screenshot 2022-07-01 at 9 46 42" src="https://user-images.githubusercontent.com/36267628/176839671-7ff761ad-9dc5-4eb1-8d14-7801b3650e7e.png">

If we add `.xsjs` to the path in `DIRIGIBLE_ODATA_HANDLER_EXECUTOR_ON_EVENT=xsodata/wrappers/onEvent` in the `dirigible.properties` file they seem to be working fine.

**Comment by vmutafov** [comment]
Fixed with: https://github.com/SAP/xsk/pull/1794
