### ISSUE TITLE
Table creation against PostgreSql database is not working

### ISSUE THREAD

**Issue by LiliyaLazarova** [SAP/xsk#176]
**Describe the bug**
Integration test for table creation against the PostgreSQL database has been created and running the test didn't create the table. 
Variables' values during debuging:
connection=1703040426, URL=jdbc:postgresql://localhost:32832/test?loggerLevel=OFF, UserName=test, PostgreSQL JDBC Driver
caseSensitive = true
sql = CREATE TABLE table-itest::sampletable_hanaxsclassic ( ID INTEGER  DEFAULT 20  NOT NULL , NAME NVARCHAR (20) NOT NULL , JOB NVARCHAR (20) NOT NULL , NUMBER INTEGER  DEFAULT 444  NOT NULL , PRIMARY KEY ( "ID" ), CONSTRAINT "MYINDEX" UNIQUE ( "ID" ), CONSTRAINT "MYINDEX10" UNIQUE ( "JOB" , "NAME" ))

Checking the query in DBeaver against postgresql db was showing that table creation is possible if namespace::table_name (table-itest::sampletable_hanaxsclassic ) is surrounded by "" and the name of the columns defined in Primary key and index constraints are NOT surrounded by "".

**Comment by Wildflowerr** [comment]
Fixed with https://github.com/SAP/xsk/pull/189/commits/bc1e29b583e7ad22c301077251a8cf66b49c0be4
