### ISSUE TITLE
[API] $.import

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#18]
**$.import** API

https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.html

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/api/api-xsjs/src/main/resources/xsk/import

**Comment by vanolincikus** [comment]
Tests added :  https://github.com/SAP/xsk/pull/243
Documentation: https://github.com/SAP/xsk/wiki/api-import
