### ISSUE TITLE
[Research] Kyma - Buildpacks, Paketo, Kpack

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#188]
Research the Docker Registry component and potential usage in [Kyma](http://kyma-project.io/).

Components:
- CNCF Buildpacks
- Paketo
- Kpack

**Comment by krasimirdermendzhiev** [comment]
![diagram-Diagram (1)](https://user-images.githubusercontent.com/82384876/118464111-29defb80-b709-11eb-9616-57217768ab69.png)


![diagram-Different](https://user-images.githubusercontent.com/82384876/118463847-e5536000-b708-11eb-81fb-46c7b3897e33.png)

**Comment by ThuF** [comment]
@krasimirdermendzhiev should we consider the research finished and close the issue?
