### ISSUE TITLE
[Parsers] - error for not supportable Db dialect

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#201]
Add exception if a given DB is not supported in processors.

For example if we provide postgress Syntax in .hdbview file the processor should noh have set version of the hana and an error should be thrown that we are not supporting this DB  dialect.

Check the XSKViewCreateProcessor.

**Comment by LiliyaLazarova** [comment]
Fixed with https://github.com/SAP/xsk/pull/242 and https://github.com/SAP/xsk/pull/228
