### ISSUE TITLE
[Research] Waypoint on Kyma

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#226]
Reasearch for Waypoint on Kyma

**Comment by krasimirdermendzhiev** [comment]
## What is Waypoint?

Waypoint is a tool that enables developers to describe how to get their applications from development to production in a single file and deploy using a single command: waypoint up. After deployment, Waypoint provides tools such as logs, exec, and more to validate and debug any deployments. Waypoint is fully extensible based on a plugin system which allows Waypoint to work with any tools and platforms.

## Kyma 

Kyma is a platform for extending applications with serverless functions and microservices.

## Waypoint usage in Kyma

Resources:
- Waypoint cli - https://learn.hashicorp.com/tutorials/waypoint/get-started-install
- Kyma - local or cluster
- Application folder

**Comment by ThuF** [comment]
Waypoint sample [file](https://github.com/hashicorp/waypoint-examples/blob/main/kubernetes/java/waypoint.hcl):
```javascript
project = "example-java"

app "example-java" {
    build {
        use "pack" {
            builder="gcr.io/buildpacks/builder:v1"
        }
        registry {
              use "docker" {
                image = "example-java"
                tag   = "latest"
              }
            }
    }

    deploy {
      use "kubernetes" {
        namespace = "default"
        probe_path = "/"
        service_port = 8080
      }
    }

    release {
      use "kubernetes" {
        node_port = 32000
      }
    }
}
```
