### ISSUE TITLE
[Migration Tools] Research where exactly to add the the UI wizard for XS app migrations

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#232]

**Comment by ThuF** [comment]
It could be provided either as standalone application (running on XSK/Dirigible) or as standard Dirigible Perspective/View.

Sample Perspective and View could be found here: https://github.com/StanZGenchev/ide-gmn

**Comment by vmutafov** [comment]
As discussed internally, the UI would be implemented as a standard Perspectiv.
