### ISSUE TITLE
[Migration Tools] Research where to add the backend part of the migration tool

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#234]

**Comment by ThuF** [comment]
The backend could be implemented as JavaScript service(s), leveraging Dirigible’s APIs:
- https://www.dirigible.io/api/http/rs/
- https://www.dirigible.io/api/database/query/
- https://www.dirigible.io/samples/database-dynamic/

**Comment by vmutafov** [comment]
As discussed internally, the backend would initially be a NodeJS application (in order to reuse already existing code) started by a REST service implemented in the XSK project.
