### ISSUE TITLE
[Parsers] hdbprocedure

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#24]
**hdbprocedure** parser

https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.02/en-US/93de88bf2c8242179647e40f958c24e5.html

Add tests
Update documentation

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/engines/engine-core/src/main/java/com/sap/xsk/hdb/ds/parser/hdbprocedure

**Comment by antoanetamh** [comment]
Functionality is tested on HANA2. 
Documentation is updated: [Wiki](https://github.com/SAP/xsk/wiki/Parser-hdprocedure)
