### ISSUE TITLE
Change the default TrustedStore within net API on demand

### ISSUE THREAD

**Issue by BorisNen** [SAP/xsk#240]
This issue is related to:
1. Issue -> https://github.com/SAP/xsk/issues/20
2. Module -> https://github.com/SAP/xsk/tree/main/modules/api/api-xsjs/src/main/resources/xsk/http
3. Documentation -> https://github.com/SAP/xsk/wiki/class-net.http.Client

Implement the setTrustStore(trustStore) method within the net.http.Client class.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
