### ISSUE TITLE
[Migration Tools] Provide a way for the user to select a database in the migration UI

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#254]
It would be great if the user could select the database he wants to use for the migration in a dropdown similar to the Delivery Units one. This would probably require some UI/UX adjustments because we would need to execute the `list-dbs` command on the backend and after that display the dropdown to the user. We could discuss this before implementing the task.

Related to: https://github.com/SAP/xsk/issues/253

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/374
