### ISSUE TITLE
[Parsers] hdbdd

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#26]
**hdbdd** parser

https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/e8c150fde4614804831c63a67224ffa8.html
https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/adb056accefa46828b5cc806e11aa6ed.html
https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/cf394efd3fb4400f9c09d10315028515.html
https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/78746b112d794f459978eb55b20a8a6f.html
https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/ad036c56b5e545ae8b31ece0ab95379f.html

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/parsers/parser-hdbdd

**Comment by delchev** [comment]
- "using" clause support (cross-file references)
- "@Catalog" support
- @SearchIndex.text.enabled support
- @SearchIndex.fuzzy.enabled support
- Complex Types definition support
- Comments support
- Multiple Contexts support

**Comment by antoanetamh** [comment]
Issue: https://github.com/eclipse/dirigible/issues/797

**Comment by ThuF** [comment]
Fixed with #395
