### ISSUE TITLE
[Database] Implement strategy for handling the scheme definition of db artifacts

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#263]
For many development artifacts, like stored procedures, we need to remove the Schema references.
In the example below, the artifact definition is coming with the "MYSCHEMA". 
This schema need to be removed.

For example:
```
PROCEDURE "MYSCHEMA"."hdb_view::OrderProcedure" ()
   LANGUAGE SQLSCRIPT
   SQL SECURITY INVOKER
   --DEFAULT SCHEMA <default_schema_name>
   READS SQL DATA AS
BEGIN
   /*************************************
       Write your procedure logic
   *************************************/

      SELECT * FROM "hdb_view::Item";
END
```

- It does not matter if the definition is of HANA v1 or Hanav2, the schema need to be removed.

For that reason we need to introduce a XSK strategy environment variable, that will cover two case:
 - Automatically remove/ignore existing schema definition when processing the artifact
 - Manual. In this case an exception will be throw nad the user will have to handle manually the removal of the schemas

**This strategy need to be applied for all DB artifacts that XSK handle**

**Comment by ThuF** [comment]
Environment variable to be introduced and the schema name to be skipped, when enabled.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
