### ISSUE TITLE
[Parsers] hdbview

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#28]
**hdbview** parser

https://help.sap.com/viewer/cc2b23beaa3344aebffa2f6e717df049/2.0.03/en-US/78dcb8e2f4f14b53b0d333bcd24f8721.html

New:
https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.02/en-US/2bf9a6f2db824fbd84315196a9c318d5.html

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/parsers/parser-hdbview

**Comment by delchev** [comment]
Depends on:
https://github.com/SAP/xsk/issues/62

**Comment by antoanetamh** [comment]
Tested on HANA2 db.
Documentation is updated: [Wiki](https://github.com/SAP/xsk/wiki/Parser-hdbview)

**Comment by antoanetamh** [comment]
Add functionality to import HANA v1 and HANA v2 syntax content
