### ISSUE TITLE
[Parsers] hdbsynonym

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#29]
**hdbsynonym** parser

https://help.sap.com/viewer/cc2b23beaa3344aebffa2f6e717df049/2.0.03/en-US/5278b5979128444cb6fffe0f8c2bf1e3.html

New:
https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.02/en-US/aad1653a9b95422089fec53f48c2899e.html

**Comment by antoanetamh** [comment]
Depends on issue: https://github.com/eclipse/dirigible/issues/770
We have implemented a workaround until the issue is fixed

**Comment by antoanetamh** [comment]
Depends on issue https://github.com/eclipse/dirigible/issues/774
