### ISSUE TITLE
Missing docker image in docker hub

### ISSUE THREAD

**Issue by GrozevJunior** [SAP/xsk#3]
Step "Pulling images" in the README file: The command docker pull dirigiblelabs/xsk-server does not work, because the image specified is missing in the docker hub, we should add it.

**Comment by ThuF** [comment]
Image [dirigiblelabs/xsk](https://hub.docker.com/r/dirigiblelabs/xsk) is now available and the README.md was updated accordingly: https://github.com/SAP/xsk/commit/e6760b91f189461a611e16a5a2d337a0848e0455
