### ISSUE TITLE
[Parsers] xsodata - antlr4 - Service, Entity

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#30]
**xsodata** parser

https://help.sap.com/viewer/b3d0daf2a98e49ada00bf31b7ca7a42e/2.0.03/en-US/502dbde2cbeb4f27b0e9b9887b0097b7.html

Samples:
HANA v1:
https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/1.0.12/en-US/02e91608eb174dcea6d544aad6ea2e12.html
HANA v2: 
https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.05/en-US/34c4b422010c45a795362d8ac6a32638.html?q=hints

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/parsers/parser-xsodata

**Comment by delchev** [comment]
- create support
- update support
- delete support
- event handlers support (create using, delete using)
- permissions and authorization support
- aggregates always support
- parameters via entity support

**Comment by antoanetamh** [comment]
https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/1.0.12/en-US/73a801f25cbf425994f22b06d3850591.html

**Comment by antoanetamh** [comment]
https://github.com/SAP/xsk/wiki/Parser-xsodata
