### ISSUE TITLE
[Parsers] xsaccess

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#31]
**xsaccess** parser

https://help.sap.com/viewer/400066065a1b46cf91df0ab436404ddc/1.0.12/en-US/5fe3b123826d4503aa66eb955a002821.html

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/engines/engine-core/src/main/java/com/sap/xsk/xsaccess/

**Comment by dpanayotov** [comment]
Scope for v0.11.0:
* xspriviliges file for role definition
* xsaccess parser that processes the authorization field
* permission check in oauth filter for the specified authorization in the xsaccess (nearest to the accessed resource takes precedence)

**Comment by dpanayotov** [comment]
Parser needs to be adjusted to process correctly the `authentication` field. To be tracked in #550
