### ISSUE TITLE
[ENGINE] Renaming of arrtifacts

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#328]
How should the XSK behave if the user decide to rename already imported artifact?

For example:
- we have imported a table1.hdbtable with some data.
- the user decide to rename the file to table2.hdbtable

The current behavior the XSK will create e a new table2.
table1 will still exist.

**Comment by delchev** [comment]
decreasing priority and postpone the issue

**Comment by dpanayotov** [comment]
to be tracked in #640
