### ISSUE TITLE
[ENGINE] Delete records are not cleared from XSK_DATA_STRUCTURES

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#350]
Steps to reproduce:
1. **Import** some non empty project
2. **Publish** the project
3. Check in the repository that the files exist 
4. Check in `XSK_DATA_STRUCTURES` that a record exist
5. **Unpublish** the project
6. Check in the repo that files do not exist
7. Check in `XSK_DATA_STRUCTURES` that the record is removed ---> ISSUE

The record in `XSK_DATA_STRUCTURES` is not removed, but it should be.

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/107

**Comment by ThuF** [comment]
To be resolved with #883
