### ISSUE TITLE
[Parsers] hdbtablefunction

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#36]
**hdbtablefunction** parser

https://help.sap.com/viewer/b3d0daf2a98e49ada00bf31b7ca7a42e/2.0.04/en-US/18a94543fe3f41f1b29e7c439f255b95.html

**Comment by antoanetamh** [comment]
Functionality is tested on HANA2. 
Documentation is updated: [Wiki](https://github.com/SAP/xsk/wiki/Parser-tablefunction)
