### ISSUE TITLE
[Parsers] calculationview

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#37]
**calculationview** parser

https://help.sap.com/viewer/fc5ace7a367c434190a8047881f92ed8/2.0.04/en-US/050f14f7a6d94d2da905b0a4072ba546.html

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/parsers/parser-calculationview

**Comment by ThuF** [comment]
Related to:
- https://github.com/SAP/xsk/issues/44
- https://github.com/SAP/xsk/issues/103

**Comment by dpanayotov** [comment]
Progress to be tracked in #44
