### ISSUE TITLE
[Parsers] hdbcalculationview

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#38]
**hdbcalculationview** parser

https://help.sap.com/viewer/c2cc2e43458d4abda6788049c58143dc/2020_04_QRC/en-US/3db2a35e714e4f6e9711fb62997d0c5c.html

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/parsers/parser-hdbcalculationview

**Comment by ThuF** [comment]
Related to:
- https://github.com/SAP/xsk/issues/44
- https://github.com/SAP/xsk/issues/103

**Comment by dpanayotov** [comment]
Progress to be tracked in #44

**Comment by dpanayotov** [comment]
Progress to be tracked in #44
