### ISSUE TITLE
[Migration Tools] Publish project at the end of the  migration process

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#383]
Currently, the XSK synchronizers are run on a time-based schedule. This may result in a project being migrated but still not having the database tables, views, etc. created in the XSK environment. We could run the necessary synchronizers right after the project is migrated in order to mitigate that concern.

**Comment by ThuF** [comment]
Synchronizers were improved as part of: https://github.com/eclipse/dirigible/issues/1063.

**Comment by ThuF** [comment]
An improvement would be to add a checkbox in the last page of the migration wizard to ask the user wether to **Publish** the imported project(s).

**Comment by dpanayotov** [comment]
Automatic publishing of the project may not be always what's desired - ie there may be additional manual steps the user needs to do before triggering the publishing.
It'd be better to have the option (via a checkbox) to select whether to publish or not.

**Comment by ThuF** [comment]
@vmutafov, @dpanayotov let's agree on having a checkbox on the last screen, whether to publish the project or not (false/unchecked by default).
