### ISSUE TITLE
[Migration] Details about supported functionalities before executing migration

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#390]
Step in the wizard to list all types of artefacts found with respective support flag.
This is useful when the user would like to decide whether to continue with the migration at all.

1. Trigger migration wizard
2. Load DU
3. Migration wizard processes artifacts (parsing, etc.)
4. Display page with information what is not supported and needs adjustment
4.1. CalculationViews referencing objects not created via hdbtable/hdbdd - need to manually create hdbsynonym (for example referencing schemas and tables external to the application / created manually)
4.2. Access to the schema and the objects in external schemas must be explicitly manually granted to the XSK user and is out of scope for XSK automation.
4.3. CalculationViews have filter expression that needs to be converted via HANA Studio
4.4. If using `_SYS_REPO` or `$.repo` needs to be adjusted
4.5. EFFECTIVE_APPLICATION_PRIVILEGES
4.6. SYS_XS
4.5. If using reserved keywords - they need to be changed (ie `ROW` as variable name) - in all hdb artifacts 
4.6. information that `VARCHAR` will be automatically handled and converted to `NVARCHAR` when making creating db artifacts (and more)
4.7. Absolute paths to artifacts in HANA must be changed to relative paths (ie /sap/hana/ui5 to be changed )
4.8. Details about using search index that it needs to be adjusted to be put in queries (link to hana cloud documentation)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
