### ISSUE TITLE
[Parsers] hdi

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#40]
**hdi** parser

**Comment by delchev** [comment]
Module:
https://github.com/SAP/xsk/tree/main/modules/engines/engine-core/src/main/java/com/sap/xsk/hdb/ds/parser/hdi

**Comment by Wildflowerr** [comment]
Fixed with https://github.com/SAP/xsk/pull/173/commits/9ba0ec19ae03a6b5096946d457b92b7e240c1161 .
