### ISSUE TITLE
[Documentation] API - $.import

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#404]
Add documentation in the www.xsk.io site, API section for the $.import API, based on the [Wiki](https://github.com/SAP/xsk/wiki/api-import).

Sample page could be found [here](https://www.xsk.io/api/%24.request/).

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/18

**Comment by vanolincikus** [comment]
Done --> https://github.com/SAP/xsk/pull/411
