### ISSUE TITLE
[Documentation] API - $.util

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#405]
Add documentation in the www.xsk.io site, API section for the $.utl API, based on the [Wiki](https://github.com/SAP/xsk/wiki/api-util).

Sample page could be found [here](https://www.xsk.io/api/%24.request/).

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/16

**Comment by vanolincikus** [comment]
Done --> https://github.com/SAP/xsk/pull/411
