### ISSUE TITLE
[Documentation] API - $.util.codec

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#406]
Add documentation in the www.xsk.io site, API section for the $.util.codec API, based on the [Wiki](https://github.com/SAP/xsk/wiki/api-util.codec).

Sample page could be found [here](https://www.xsk.io/api/%24.request/).

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/21

**Comment by vanolincikus** [comment]
Done --> https://github.com/SAP/xsk/pull/411

**Comment by vanolincikus** [comment]
Done --> https://github.com/SAP/xsk/pull/411
