### ISSUE TITLE
.hdbtable indeces type in not taken into account

### ISSUE THREAD

**Issue by Wildflowerr** [SAP/xsk#410]
If we have the following hdbtable definition:
```text
table.schemaName = "DBADMIN";
table.temporary = true;
table.tableType = COLUMNSTORE;
table.loggingType = NOLOGGING;
table.columns = [
	{name = "Col1"; sqlType = NVARCHAR; nullable = false; length = 20; comment = "dummy comment";},
	{name = "Col2"; sqlType = INTEGER; nullable = false;},
	{name = "Col5"; sqlType = NVARCHAR; nullable = false; length = 20; defaultValue = "Defaultvalue";},
    {name = "Col66"; sqlType = NVARCHAR; nullable = true; length = 20; defaultValue = "Defaultvalue";},
    {name = "Col77"; sqlType = NVARCHAR; nullable = true; length = 20; defaultValue = "Defaultvalue";}];
table.indexes =  [
	{name = "BB112"; unique = true; order = DSC; indexColumns = ["Col2"];},
	{name = "BB212"; unique = true; order = DSC; indexType = B_TREE; indexColumns = ["Col1"];}];
table.primaryKey.pkcolumns = ["Col1", "Col2","Col5"];
```

the SQL to be generated is:
```sql
CREATE COLUMN TABLE "DBADMIN"."p1::file" ( "Col1" NVARCHAR (20) NOT NULL , "Col2" INTEGER  NOT
 NULL , "Col5" NVARCHAR (20) DEFAULT 'Defaultvalue'  NOT NULL , "Col66" NVARCHAR (20) DEFAULT 'Defaultvalue'  , "Col77" NVARCHAR (20) DEFAULT 'Defaultvalue'  , PRIMARY KEY("Col1" , "Col2" , "Col5") , CONSTRAINT "BB112" UNIQUE ( "Col2" ), CONSTRAINT "BB212" UNIQUE ( "Col1" ))
```
As you can deduce by the snippet, the index type is not considered at all. All indeces have been created as normal constraints. This might be a **limitation** on our side.

**Comment by LiliyaLazarova** [comment]
Investigation:
No matter what the index type is (`B_TREE `or `CPB_TREE`) in case of table.tableType = COLUMNSTORE; the value persisted in the DB is `INVERTED VALUE`. 
If the indexType is set to `B_TREE `or `CPB_TREE` when creating ROW table

```
CREATE ROW TABLE "DBADMIN"."row"( "Col1" NVARCHAR (20) NOT NULL , "Col2" INTEGER  NOT
 NULL , "Col5" NVARCHAR (20) DEFAULT 'Defaultvalue'  NOT NULL , "Col66" NVARCHAR (20) DEFAULT 'Defaultvalue'  , "Col77" NVARCHAR (20) DEFAULT 'Defaultvalue'  , PRIMARY KEY("Col1" , "Col2" , "Col5") , CONSTRAINT "I1" UNIQUE BTREE ( "Col2" ), CONSTRAINT "I2" UNIQUE CPBTREE ( "Col1" ))
```
, then the index type is persisted as BTREE UNIQUE and CPBTREE UNIQUE

![image](https://user-images.githubusercontent.com/20951516/140478781-bf368ce3-6503-4fd2-bfe2-b698f28ce7f1.png)

Currently we don't support ROW table creation, so a new issue will be created this to be implemented, so it will make sense to have indexType support as well.

**Comment by LiliyaLazarova** [comment]
Refference for index Types: 
https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/20a7044375191014a939f50ae14306f7.html

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1270

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/1289
