### ISSUE TITLE
[CORE] Refactor the XSKDataStructureTopologicalSorter

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#423]
The code in XSK and Dirigible is duplicate.
`XSKDataStructureTopologicalSorter`

**Comment by dpanayotov** [comment]
related to
- https://github.com/eclipse/dirigible/issues/1607

To adopt https://github.com/eclipse/dirigible/commit/0536706e9e837c9c5a87c950a350cffa3b8a9518

**Comment by dpanayotov** [comment]
obsolete
