### ISSUE TITLE
[HDBDD] Issue with Namespace Rule

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#432]
We have the following project structure:
![image](https://user-images.githubusercontent.com/44926767/130778979-9cfb0ee4-5e44-4798-b1f3-f1ee2e9f438c.png)

`c.s.x.hdb.ds.facade.XSKHDBCoreFacade - Failed to parse file: /HCO_DCS_GSTR1/sap/slh/dcs/gstr1/table/EINVOICE_HEADER_PULLED_TONI.hdbdd. Error at line: 1. Namespace does not match the file directory.`

The Error is thrown when comparing
"HCO_DCS_GSTR1.sap.slh.dcs.gstr1.table" vs "sap.slh.dcs.gstr1.table"

```
 @Override
    public void enterNamespaceRule(CdsParser.NamespaceRuleContext ctx) {
        String packageName = ctx.members.stream().map(Token::getText).collect(Collectors.joining("."));
        if (!packageName.equals(getExpecteNamespace())) {
            throw new CDSRuntimeException(
                    String.format("Error at line: %s. Namespace does not match the file directory.", ctx.members.get(0).getLine()));
        }
        this.packageId = packageName;
    }
```

**Comment by GrozevJunior** [comment]
As we discussed today, the string 'HCO_DCS_GSTR1' is not the project name or if it was, it should have been included in the namespace of the file. The top folder in the case should be 'sap' in order for the namespace to match.
