### ISSUE TITLE
[TEST] Implement reusable js tests executor

### ISSUE THREAD

**Issue by tdermendjiev** [SAP/xsk#436]
Currently there are javascript tests in some of the modules which are executed by repeated logic which could be abstracted.

We should create javascript tests executor class which implements all necessary logic for resolving the js scripts' paths and loading them.

**Comment by dpanayotov** [comment]
Related to https://github.com/eclipse/dirigible/pull/1156

**Comment by ThuF** [comment]
Moving back to **To do** as there were no recent updates.

**Comment by vmutafov** [comment]
Closing as there is currently the `GraalVMCustomJSExecutorTest` class that could be used.
