### ISSUE TITLE
[CalculationView] [Parsers] Migrate to hdbcalculationview

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#44]
calculationview to hdbcalculationview migration task to be implemented as action in the Web IDE. Due to the differences of the format and handling of the old and new calculation views, there is a need of a pre-processing before the artefact hdbcalculationview be added to the HDI container along with the corresponding synonyms.

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/103

**Comment by dpanayotov** [comment]
Scope for v0.11.0:
Test migration through HANA Studio of calculation view and whether migration to XSK works with the migrated artifact.

**Comment by dpanayotov** [comment]
Split into
* #707 
* #789 
* #790 
* #791 
* #792

**Comment by dpanayotov** [comment]
subtasks resolved
