### ISSUE TITLE
[Security] Migration Tool - Close Database Tunnel

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#453]
As of now the `neo close-db-tunnel` command is never executed, so by default the tunnel is closed after 1 hour.
**Impact:** The datasource to the target HANA database is accessible in the `Database` perspective, under the `dynamic` datasource section.
**Proposal:** Execute the `neo close-db-tunnel` command as a last step of the migration process.

**Comment by ThuF** [comment]
@vmutafov could you confirm that the `close-db-tunnel` commands is executed at the end of the migration process? If so, please close this issue as fixed.

**Comment by vmutafov** [comment]
Yes, it is executed as a final step in the migration process.
