### ISSUE TITLE
[Migration] Add better error handling in the JS backend

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#456]
Currently, we do not provide good error responses to the frontend. We should change this and return proper status codes and error messages in order to debug any issues easily and tell the user if he has provided wrong credentials for example.

**Comment by ThuF** [comment]
You could try the `catch()` function from the [RS](https://www.dirigible.io/api/http/rs/) API. Example could be found [here](https://github.com/dirigiblelabs/ide-documents/blob/master/ide-documents/api/documents.js).

**Comment by vmutafov** [comment]
Fixed with: https://github.com/SAP/xsk/pull/761
