### ISSUE TITLE
[Migration Tools] Add a selenium test for the migration

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#457]
We should add a selenium test to run a migration of a simple app and observe the imported files in the XSK. The test would include several steps:
1. Navigate to the Migration perspective in XSK
2. Provide Neo credentials - we should discuss which Neo landscape should we use
3. Provide Hana credentials - we should discuss which HANA instance should we use
4. Select an XSK Workspace and HANA delivery unit 
5. Execute the migration
6. Assert the project is successfully imported in XSK and the files' content is correct

**Comment by Fluctuationqt** [comment]
Feature added with: https://github.com/SAP/xsk/pull/484
