### ISSUE TITLE
[CI/CD] Configure the nightly build to run on Windows

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#458]
Currently, the nightly build of the XSK runs on ubuntu only. We should run it on windows too in order to quickly find any regressions happening on the Windows OS. 
There are some steps in the nightly build that should be changed depending on the OS. For example, some dependencies are being downloaded using Linux-specific package managers and some tools used in the GitHub action may not be available on Windows.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
