### ISSUE TITLE
[CORE] Log processors errors using ProblemsFacade

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#465]
Implement it to all processors.
This will help for customer testing.

Using method `logProcessorsErrors()` in [class](https://github.com/SAP/xsk/blob/main/modules/engines/engine-commons/src/main/java/com/sap/xsk/utils/XSKCommonsUtils.java) currently implemented for processors of:
- [x] hdb
- [x] hdbti
- [x] hdi
- [x] xsjob
- [x] xsodata
- [ ] xssecurity

**Comment by ThuF** [comment]
**xssecurity** related logging of problems to be tracked in separate issue.
