### ISSUE TITLE
[Parser] HDBTI ->import csv file with empty line

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#491]
when import csv file with empty line, an exception is thrown at line:
process:84, XSKHDBTIProcessor (com.sap.xsk.hdbti.processors)

Research if this is the XSK classic behavior.
If it is then throw some more user friendly exception

**Comment by antoanetamh** [comment]
duplicate on https://github.com/SAP/xsk/issues/520

**Comment by ThuF** [comment]
Fixed with: #520
