### ISSUE TITLE
[CI/CD] Performance Tests

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#494]
Create performance tests for the following scenarios:
1. API Calls:
    - Authentication & Authorization
    - Execute CRUD Database Statements (HANA Cloud)
    - Measure the Response Time
2. UI (with Selenium?):
    - Login
    - Load page
    - CRUD data through the UI
    - Measure the scenario execution time

We want also to compare the results with the following applications:
- Pure Java application (Spring?)
- Eclipse Dirigible application
- XSK application

We want also to compare the results on different infrastructure:
- Pure Kubernetes
- Kyma
- Cloud Foundry

We want also to test the optimal resource limits configuration per Kubernetes deployment - https://github.com/SAP/xsk/issues/493

**Comment by krasimirdermendzhiev** [comment]
Performance test for infrastructure and applications
Related: https://github.com/SAP/xsk/issues/895

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
