### ISSUE TITLE
[IDE] No option to create a `.xsjs` file

### ISSUE THREAD

**Issue by slavipande** [SAP/xsk#499]
**Bug Description**
Currently, there's no option to create a `.xsjs` file through `right click --> New--> filetype`.  None of the options available through this menu creates a `.xsjs` file.
![2021-09-14_13-17-41](https://user-images.githubusercontent.com/46915717/133240309-047d1004-5657-4e34-a14d-3622ee61f0b9.png)

**To Reproduce**
1. Right-click on your project in the `Workspace` view of the `Workspace` perspective
2. Hover over 'New'
3. Search for an option to create a `.xsjs` file

**Expected behavior**
Such option should be available.

**Screenshots**
Provided above.

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version: 93.0.4577.63 (Official Build) (64-bit)

**Comment by delchev** [comment]
postpone a bit due to relation to dev scenario

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/428
