### ISSUE TITLE
[Documentation] Incomplete code sample for $.import

### ISSUE THREAD

**Issue by slavipande** [SAP/xsk#504]
**Description of the bug**
The code sample under section **Sample Usage** on this page is incomplete: https://www.xsk.io/api/import/. I've provided a screenshot below for more context.

**To Reproduce**
1. Go to https://www.xsk.io/api/import/
2. Copy the code sample
3. In the xsk trial landscape, create a new project and a new .xsjs file
4. Paste the code sample and save the file.
4. See error in the **Preview** view.

**Expected behavior**
The code sample should work.

**Screenshots**
![2021-09-15_14-48-56](https://user-images.githubusercontent.com/46915717/133428371-962c3273-f1f6-488d-bc7e-a631d3f64d9b.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by cheezus1** [comment]
confirmed
