### ISSUE TITLE
[Documentation] Code sample for $.net.SMTPConnection returns an error

### ISSUE THREAD

**Issue by slavipande** [SAP/xsk#512]
**Description of the bug**
The code sample under section Sample Usage on this page returns an error: https://www.xsk.io/api/net.SMTPConnection/. I've provided a screenshot below for more context.

**To Reproduce**

1. Go to https://www.xsk.io/api/net.SMTPConnection/
2. Copy the code sample
3. In the xsk trial landscape, create a new project and a new .xsjs file
4. Paste the code sample and save the file.
5. See error in the **Preview** view.

**Expected behavior**
The code sample should work.

**Screenshots**
![2021-09-15_15-18-55](https://user-images.githubusercontent.com/46915717/133432248-213a5883-72a2-48b0-b66e-826d7126aac0.png)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by aihanrashidov** [comment]
Related to #513 
Documentation update - https://github.com/SAP/xsk/commit/4337711fac00e44715741a62c3e2182f4e108e9e

**Comment by ThuF** [comment]
Closing the issues as resolved. Additional step-by-step tutorial could be found here: https://blogs.sap.com/2020/02/05/sending-e-mails-with-the-eclipse-dirigible-mail-api/
