### ISSUE TITLE
[Documentation] Code sample for $.response returns an error

### ISSUE THREAD

**Issue by slavipande** [SAP/xsk#515]
**Description of the bug**
The code sample under section Sample Usage on this page returns an error: https://www.xsk.io/api/response/. I've provided a screenshot below for more context.

**To Reproduce**

1. Go to https://www.xsk.io/api/response/
2. Copy the code sample
3. In the xsk trial landscape, create a new project and a new .xsjs file
4. Paste the code sample and save the file.
5. See error in the **Preview** view.

**Expected behavior**
The code sample should work.

**Screenshots**
![2021-09-15_15-28-07](https://user-images.githubusercontent.com/46915717/133433633-0e35227a-5b10-4f7d-a23b-b3a941ddbd63.png)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by aihanrashidov** [comment]
The sample code expects the request method to be of type `GET` and looks for a `color` query parameter. In case the parameter is provided with for example `?color=red` the `filterCarsByColor()` method will be invoked. And in case it is missing we enter the else clause where a message for missing `color` parameter is returned. I will modify the sample so it is not confusing.

**Comment by aihanrashidov** [comment]
Sample update - https://github.com/SAP/xsk/commit/0b8521a45aed3ef6e2e791801bc87dce484936d6

**Comment by delchev** [comment]
confirmed
