### ISSUE TITLE
[Migration] Add an initial screen for the Migration perspective

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#525]
Currently, the initial screen of the migration perspective is for entering your credentials and then starting the migration. 
We should change the initial screen to be a list of migrations with their status (completed, failed, canceled, running, etc.). On this screen, the user should have a button for starting a migration which would lead to the current initial screen. We should be able to "open" a migration that is currently running and being navigated to the step on which the migration is at this point in time.

edit @dpanayotov:
- Add a checkpoint when the diff editor is reached so that the migration can be continued from there. Steps before that won't have a checkpoint

**Comment by ivanvolkoff** [comment]
Issue is resolved by https://github.com/SAP/xsk/pull/957
