### ISSUE TITLE
[Migration] Post Action: CalculationViews

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#570]
_SYS_BIC is used in XS classic with HANA1, but it is missing in HANA 2.
The schema is used with Calculation view logic

- [x] **1. Different calculation view naming**

In XS Classic: `SELECT * FROM "_SYS_BIC"."sap.slh.dcs.gstr1/CV_GSTR1_NIL_SUMM"`
in HDI:         ` SELECT * FROM  "XSK_HDI_EXT"."com.sap.xsk.samples::CustomersCalcView"`

Target:
1. Process each artifact and find usage of `_SYS_BIC`
2. Change `_SYS_BIC` to the HDI container 
3. Change the syntax of the calcview to be with `::`

Artifacts which should be processed:
* xsjs and xsjslib
* hdbtablefunction
* calculationview

Progress to be tracked in:
- https://github.com/SAP/xsk/issues/891

- [x] **2. Different Schemas**
In XS Classic
When Calculation View is created 4 artifacts are created:
![image](https://user-images.githubusercontent.com/44926767/136534625-e59d37ec-a6dd-4081-b3cf-411cb4659408.png)

For Hana 2, we need to replace the _SYS_BIC with the name of the HDI container where the calculation view is deployed

**@dpanayotov: Done - calcviews are added to .hdi file which is then deployed to the HDI container**

- [x] **3. Creating of PUBLIC synonym**
From the image above we can see that XS Classic is creating public synonym  for the calculation view.
**@dpanayotov: Being addressed with #797**

**Comment by ThuF** [comment]
The remaining tasks will be tracked in:
- https://github.com/SAP/xsk/issues/891
