### ISSUE TITLE
[HDI] Research - hdbdd table is created in user schema

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#578]
Import hdi-simple example
The XSK_HDI_SIMPLE_TABLE table is created in user schema, if you are logged as ADMIN user - that will be the ADMIN schema. --> this should not happen

The XSK_HDI_SIMPLE_TABLE table is created inside the HDI schema , which is the XSK_HDI_SIMPLE schema --> this is the expected behavior

**Comment by ThuF** [comment]
@MarinHadzhiev do we have any updates here?

**Comment by MarinHadzhiev** [comment]
@ThuF WIP

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
