### ISSUE TITLE
URLs in imported XS project not resolved

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#599]
**Describe the bug**
URLs in code written in XSC are relative to the repository and package they're in. However, routes in XSK are prefixed with `/services/v4/xsk` which needs to be added to all paths in the code.

Let's say I'm following this tutorial - https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/6863e48a71aa48479ab4183892e7e4d8.html and on Step 6 I need to call an XSJS service. In XSC I'd provide the path starting from the root and going to the xsjs file. In XSK I'd have to prefix this with `/services/v4/xsk/`.

> What version of the XSK are you using?
0.9.2

**To Reproduce**
1. Have a working project in XSC which has a JS file calling an XSJS service
2. Export the project 
3. Import in XSK
4. Try to call the JS function and see that the xsjs service cannot be resolved

**Expected behavior**
Up for discussion. I can think of some options but none seem great:
1. Serve all content from the base path and not `/services/v4/xsk/`
2. In the migration assistant parse all files and try to find a path that needs to be prefixed with `/services/v4/xsk/`

**Comment by ThuF** [comment]
@dpanayotov, another option would be to create a page in the documentation with known issues/limitations.

Also it might be possible to create a filter and forward requests containing `*.xsjs`, `*.xsodata`, etc. in the path, to the right endpoint.
