### ISSUE TITLE
[Customer project - Post action] - HANA2 DB keywords used incorrectly 

### ISSUE THREAD

**Issue by LiliyaLazarova** [SAP/xsk#602]
In XS Classic the using of key words without "" is allow, but in HAAN2 it is not.
```
schema = "SAP_INO";
query = "
    select  
            stage.CODE,
            authorization_stage.*,
            authorization.action_code,
            authorization.role_code,
            authorization.CAN_DO_ACTION
    from\"sap.ino.db.status::t_status_authorization_stage\" as authorization_stage
    left outer join \"sap.ino.db.status::t_status_authorization\" as authorization
    on authorization_stage.ID = authorization.ID_OF_STATUS_AUTHORIZATION_STAGE
    left outer join \"sap.ino.db.status::t_status_stage\" as stage
    on stage.ID = authorization_stage.ID_OF_STATUS_STAGE
    where authorization_stage.SETTING_CODE = 'OPEN_STATUS_AUTHORIZATION' and authorization_stage.Value = 1
    with read only ";

depends_on_table = ["sap.ino.db.status::t_status_authorization",
                    "sap.ino.db.status::t_status_authorization_stage",
                    "sap.ino.db.status::t_status_stage"];   

```

`Select 1 as NO From "SAP_INO"."sap.ino.db.iam::v_auth_identity_attribute"`

- [ ] "Authorization" is a keyword 
- [ ] "NO"  is a keyword and should be escaped
- [ ] "filter"
- [ ] "ROW"

Proposed solution : "authorization" keyword should be put inside the quotes if it have to be used.
Reference: https://help.sap.com/viewer/f381aa9c4b99457fb3c6b53a2fd29c02/2.0.02/en-US/888f434c5e494d6c9af82bc5db854a14.html

**Comment by dpanayotov** [comment]
Such queries might occur outside hdb files - ie there are xsjs/xsjslib files that execute SQL statement directly. 
Scope for v0.11.0 is to provide an API that returns before and after with the proposed changes to the files. Nevertheless, it should be tested that applying the `after` statements resolves the issue.

**Comment by cheezus1** [comment]
When reserved keywords are not escaped, an `SQLException` for incorrect syntax is being added to the Problems Facade. Updated the [XSK](https://www.xsk.io/) documentation accordingly.
