### ISSUE TITLE
[Customer] - Missing DB system schemas after migration to Hana 2

### ISSUE THREAD

**Issue by LiliyaLazarova** [SAP/xsk#603]
- [ ] EFFECTIVE_APPLICATION_PRIVILEGES -> 
You must have the system privilege CATALOG READ to query the following system view 
![image](https://user-images.githubusercontent.com/20951516/137117898-0a85c100-84cf-480b-8e01-18cd8563ccc8.png)
- [ ] _SYS_REPO -> 
_SYS_REPO schema represents the repository in HANA v1 , which stores the definitions of tables, views, etc., but it is removed in Hana v2.
https://launchpad.support.sap.com/#/notes/0002465027
- [ ] _SYS_XS ->
Tables from this schema are used by XSJOB service and contains data related to SAP HANA Extended Applications Services

**Comment by dpanayotov** [comment]
to be tracked in 
- #390 

Adjustments will be required
