### ISSUE TITLE
[Test] Xsjob Parser Hana Integration Test

### ISSUE THREAD

**Issue by BorisNen** [SAP/xsk#604]
Related to https://github.com/SAP/xsk/issues/32
Test should be created in modules/engines/engine-xsjob/src/itest/ and it should be under a separate maven profile.

It should perform the following steps:
1. Schedule a .xsjob file inside /itest/resources that will be persisted in XSK_JOBS
2. After persisting, the scheduler should trigger and arrive in XskJobHandler
3. The job should call a .xsjs file inside /itest/resources
4. The .xsjs file should use the $.db API to persist a row in the Hana DB
5. Assert that the .xsjs file is executed and all data has been persisted

Current problems:
Custom TestRepository and TestCollection classes have been created to overwrite LocalCollection and FileSystemRepository/IRepository.
Step 1 is completed. Step 2 displays non-deterministic execution - XskJobHandler is not accessed every time (when synchronise.js is called instead of handler.js). When it is accessed, the test is interrupted by an error within the execute method of GraalVMJavascriptEngineExecutor.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
