### ISSUE TITLE
[HDBDD] Parser Add support for all annotations

### ISSUE THREAD

**Issue by GrozevJunior** [SAP/xsk#616]
Currently we only support parsing of: 
@Catalog
@Schema

We also should be able to parse the following: 
@nokey
@GenerateTableType
@SearchIndex

Check out how first two are created - you should only provide metadata about the annotation definition and add it to the symbol table.

Methods you should look into:
SymbolTable.initAnnotations()
EntityDefinitionListener.validateAnnotation(..)
EntityDefinitionListener.compareAnnValues(..)

Also creating a factory class for all the annotations and extracting the already existing code from symbol table(concerning the annotation creation) will improve code quality and readability.

Tests after a successful implementation should be added by all means!

Note: @WithStructuredPrivilegeCheck should be investigated in more details, since it isn't clear enough from the documentation what behavior is expected!

Documentation link: 
https://help.sap.com/viewer/09b6623836854766b682356393c6c416/2.0.03/en-US/8217aac86d9748d8b034797ecc8065b6.html#

**Comment by LiliyaLazarova** [comment]
A new bug has been created, because parsing a complex file with nested structures not working and class cast exception is thrown : https://github.com/SAP/xsk/issues/678
