### ISSUE TITLE
[HDBDD] Engine Support for processing annotation data

### ISSUE THREAD

**Issue by GrozevJunior** [SAP/xsk#617]
Each Symbol.class holds a collection of annotations but currently we do nothing with the provided data.

The current processors and xsk data model should be enhanced to include the annotation data and make the expected changes in the database.

For example the @Catalog annotation is parsed and the table should be created base on the @Catalog.tableType - #COLUMN or #ROW
The @Catalog.index[] should be processed and the already existing XSKDataStructureHDBTableConstraintsModel.class should be used to create new indices. The transformation between the CatalogObjectAnnotation and the XSKDataStructureHDBTableConstraintsModel could be done in HdbddTransformer.class

Cds annotation documentation: https://help.sap.com/viewer/09b6623836854766b682356393c6c416/2.0.03/en-US/8217aac86d9748d8b034797ecc8065b6.html#

**Comment by dpanayotov** [comment]
Should be able to reuse idea from https://github.com/SAP/xsk/pull/819

**Comment by dpanayotov** [comment]
related to 
- #1198

**Comment by dpanayotov** [comment]
https://help.sap.com/viewer/9bf0d965efc74c51b0fbf177d3f96e5b/1.0.12/en-US/f7d6e1733c63488d9d568af2303251aa.html

Add support for parsing the following annotations:
* EnterpriseSearch
* EnterpriseSearchHana
* Hierarchy

**Comment by dpanayotov** [comment]
related to 
- #1280

**Comment by dpanayotov** [comment]
to be tracked in separate issues
