### ISSUE TITLE
[Parsers] The old parser of .hdbview artifact should be replaced by a new one implemented with antlr4

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#62]
SQL Views Parser
https://help.sap.com/viewer/b3d0daf2a98e49ada00bf31b7ca7a42e/2.0.03/en-US/7b1ddcdb650c44308f5bf6339ed9b4b2.html

Implement Tests
Update documentations: https://github.com/SAP/xsk/wiki/Parser-hdbview

**Comment by delchev** [comment]
Related to:
https://github.com/SAP/xsk/issues/28
