### ISSUE TITLE
[API] Unit tests

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#627]
As an XS Classics developer I want to be able to execute unit tests. Via the unit tests I want to be able to tests:

- Server side JavaScript code
- SQLScript code (stored procedures and views)
- Modeled calculation views

I need to be able to substitute original db objects with test ones.
I need to be able to collect code coverage.

Some information how it is achieved in XS Classic

- [Unit Testing SAP HANA Views – A Beginners Guide
](https://blogs.sap.com/2015/02/16/unit-testing-sap-hana-views-a-beginners-guide/#:~:text=As%20well%2C%20the%20mocking%20framework%20Mockstar%20was%20introduced,attribute%20views%2C%20analytic%20views%2C%20calculation%20views%20and%20procedures)
- [XSUnit (*Test.xsjslib)](https://launchpad.support.sap.com/#/softwarecenter/template/products/_APP=00200682500000001943&_EVENT=NEXT&HEADER=Y&FUNCTIONBAR=Y&EVENT=TREE&NE=NAVIGATE&ENR=01200314690800001945&V=MAINT&TA=ACTUAL/SAP%20HANA%20PLATFORM%20EDITION)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
