### ISSUE TITLE
[API] XSJS service does not return error on missing db connection

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#646]
**Describe the bug**
When db connection cannot be established (ie because DB is down), the XSJS service returns 200 OK with empty body

**To Reproduce**
1. Start XSK connected to HANA Cloud
2. Create file.xsjs with the following content:
```javascript
$.response.contentType = "text/html";
var output = "Hello, World !"; 

var conn = $.db.getConnection();
var pstmt = conn.prepareStatement( "select * from DUMMY" );
var rs = pstmt.executeQuery();

if (!rs.next()) {
    $.response.setBody( "Failed to retrieve data" );
    $.response.status =  $.net.http.INTERNAL_SERVER_ERROR;
} else {
    output = output + "This is the response from my SQL: " + rs.getString(1);
}
rs.close();
pstmt.close();
conn.close();

$.response.setBody(output);
```
3. Access the xsjs service and see that the response is `Hello, World !This is the response from my SQL: X`
4. Stop HANA Cloud instance
5. Again access the xsjs service and see empty response with status 200 OK

**Expected behavior**
I get an error 500

**Additional context**
Maybe check the Exception handlers and if they are covering the xsjs flow

**Comment by vmutafov** [comment]
The fix is made in https://github.com/eclipse/dirigible/pull/1663

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1663, will be available with the next release of Eclipse Dirigible.
