### ISSUE TITLE
[IDE] Problems - Location to be clickable

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#652]
**Describe the solution you'd like**
In the problems view, the location should be clickable.
1. Clear indication that the location is a link (colored)
2. When clicked, open the file in the editor and put the cursor on the problematic line
3. Expand the file tree on the left and focus the file

**Comment by BorisNen** [comment]
Issue is closed in dirigible with https://github.com/eclipse/dirigible/pull/1257
Will be available in the next release.
