### ISSUE TITLE
[IDE] Hide technical implementation details

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#661]
**Describe the solution you'd like**
Identify and replace technical implementation details with user friendly text messages.
Example: `Right click > Open with > Monaco` to be `Code Editor` for example. Monaco as the underlying editor may not make sense to be presented to the user

---

**Progress to be tracked in:**
- https://github.com/eclipse/dirigible/issues/1219

**Comment by ThuF** [comment]
@dpanayotov please transfer this issue to: https://github.com/eclipse/dirigible/issues

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1366, will be available with the next release of Eclipse Dirigible.
