### ISSUE TITLE
[IDE] Loading indicator

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#662]
**Is your feature request related to a problem? Please describe.**
There's no easy way to describe if something is loading or if it's loaded and no information is shown. 

**Describe the solution you'd like**
Whenever a view is loading content, there needs to be an indicator.

fundamentals-ngx defines budy indicator - https://sap.github.io/fundamental-ngx/#/core/busy-indicator

---

**Progress to be tracked in:**
- https://github.com/eclipse/dirigible/issues/1221

**Comment by ThuF** [comment]
@dpanayotov please transfer this issue to: https://github.com/eclipse/dirigible/issues

**Comment by dpanayotov** [comment]
to be covered with #749
