### ISSUE TITLE
[IDE] Can't close welcome screen

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#663]
**Describe the bug**
Welcome tab cannot be closed unlike any other tab

---

**Progress to be tracked in:**
- https://github.com/eclipse/dirigible/issues/1222

---

**Additional context**
![image](https://user-images.githubusercontent.com/4910295/137884244-b28d7264-0d61-4ec3-ad68-484516245cdf.png)

**Comment by StanZGenchev** [comment]
This is not a bug. It was decided a while back that the welcome screen should not be closable.
See Dirigible issue https://github.com/eclipse/dirigible/issues/900

**Comment by dpanayotov** [comment]
I think of https://github.com/eclipse/dirigible/issues/900 as temporary mitigation to the problem.
If currently there are technical limitations to solve this we should discuss them and think of how to address them.
Welcome tab is not special and is not treated specially in any other development environment

I'm reopening this to have it for the 1.0 delivery
