### ISSUE TITLE
[IDE] Delete many to prompt only once

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#664]
**Is your feature request related to a problem? Please describe.**
Marking multiple files/folders for deletion opens a confirmation prompt for each selected file.

**Describe the solution you'd like**
Only 1 confirmation pop-up is shown with a message similar to `Are you sure you want to delete the following N files?`

---

**Progress to be tracked in:**
- https://github.com/eclipse/dirigible/issues/1223

**Comment by ThuF** [comment]
@dpanayotov please transfer this issue to: https://github.com/eclipse/dirigible/issues

**Comment by dimitarquanterall** [comment]
Please, assign it to me

**Comment by dimitarquanterall** [comment]
Fixed in dirigible by https://github.com/dirigiblelabs/ide-workspace/pull/2
The issue may be closed

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1644, will be available with the next release of Eclipse Dirigible.
