### ISSUE TITLE
[IDE] Preview downloads files

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#668]
**Describe the bug**
Preview tab causes the browser to download the file that is being edited/published.

**To Reproduce**
1. Create a .websocket file
1. Open it in the editor
1. Click save
1. See that it's downloaded

**Expected behavior**
Files are not downloaded

**File types affected**
- .websocket
- .calculationview

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser: Both Safari and Chrome experience this issue

---

**Progress to be tracked in:**
- https://github.com/eclipse/dirigible/issues/1224

**Comment by ThuF** [comment]
PR merged in Eclipse Dirigible. The functionality will be available with the next release of Eclipse Dirigible.
