### ISSUE TITLE
[IDE] Can't move editor above console

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#669]
**Describe the bug**
If for some reason the file tab is moved to the side there doesn't seem to be an easy way to move it back above the console. I can also move an opened file tab to the workspace panel on the left or to the problems/console tabs on the bottom.

**To Reproduce**
1. Open XSK
2. Move file/Welcome tab to the right
3. See that the panel above is gone
4. Try to move it back

**Expected behavior**
Editor panel can be moved independent of the remaining views and should not be possible to move tabs across panels. 

---

**Progress to be tracked in:**
- https://github.com/eclipse/dirigible/issues/1225

---

**Screenshots**
![image](https://user-images.githubusercontent.com/4910295/137887973-ac33b2fa-4f4b-42f7-b3b6-32af6a8a9eb6.png)

**Comment by ThuF** [comment]
The editor should be dropped at the top section:

![Screenshot 2021-10-20 at 12 16 19](https://user-images.githubusercontent.com/4092083/138065622-6fd7af68-b1a4-4d60-8f74-936dfb89e0f7.png)

Alternatevely the **Themes** -> **Reset** functionality could be used:

![Screenshot 2021-10-20 at 12 16 43](https://user-images.githubusercontent.com/4092083/138065895-d3af6337-862a-472a-b176-f11c540c09b6.png)

**Comment by ThuF** [comment]
Dragging and dropping the editor to the very top of the screen (as in the first screenshot) should solve the issue, isn’t it?

**Comment by dpanayotov** [comment]
https://user-images.githubusercontent.com/4910295/138152414-3ae3d3b0-27bc-4240-a24c-cec815836b2b.mov

I failed to explain the exact issue - it's possible to move it, but if you for some reason decided to mess with the Welcome tab or move all tabs somewhere else it's difficult to return them to the proper place. Probably just restricting tabs to their designated panel would be the most straight forward and easy to understand solution. It's a really with low prio and a nice to have in terms of usability.
