### ISSUE TITLE
[IDE] Import functionality

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#672]
**Is your feature request related to a problem? Please describe.**
I could not easily find how to import files in the project view. I can't import multiple files. I have to switch to another tab to import a project.

**Describe the solution you'd like**
1. Adding files/folders to the workspace should use the same terminology as for projects - either `Import` or `Upload`
1.1. Currently, there's `Import` tab which is actually `Import project` and right-click on a folder/project in the tree has a button called `Upload` which allows adding only a single file. 
2. It should be possible to upload/import multiple files at the same time anywhere in the file tree
3. It should be possible to upload/import a whole folder anywhere in the file tree
4. The UX for importing files/folder should not differ from the one for importing projects. Importing a project seems strange at the moment in a separate tab with workspace selection that can be easily moved to the workspace tab

**Comment by dimitarquanterall** [comment]
It will be great to add per folder export together with per folder import, too. Just like in projects - Export/Import.

Please, assign the issue to me
