### ISSUE TITLE
[Migration] Import functionality hangs on wrong neo config

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#679]
**Describe the bug**
The migration UI hangs if incorrect Neo configuration is provided

> What version of the XSK are you using?
0.9.2

**To Reproduce**
**Case 1 - correct region, wrong credentials**
1. Open XSK
2. Go to migration tool
3. Choose correct region and subaccount
4. Enter wrong credentials
5. See loading screen forever

**Case 2 - wrong region, correct credentials**
1. Open XSK
2. Go to migration tool
3. Enter correct credentials
4. Choose region that is not the one in which the subaccount is 
5. See loading screen forever

**Expected behavior**
An error is shown saying that the credentials are incorrect or the region and subaccount combination is not correct

**Comment by vmutafov** [comment]
Fixed with: https://github.com/SAP/xsk/pull/761
