### ISSUE TITLE
[API] XSJS API - $.util.Zip()

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#684]
As an XSK developer I need to be able to use `$.util.Zip()` API. This functionality is a must in scenarios where reports are exported in order to significantly reduce the size of the files.
Example from XS Classic

```javascript
var body = "123123213";
var zip = new $.util.Zip();
zip["file1.txt"] = body;

$.response.status = $.net.http.OK;
$.response.contentType = "application/zip";
$.response.headers.set('Content-Disposition', "attachment; filename = Purchase.zip");
$.response.setBody(zip.asArrayBuffer());
```

**Comment by vmutafov** [comment]
As the Dirigible already has an [API for zipping](https://www.dirigible.io/api/io/zip/), maybe we could extend it to be a bit closer to the XS Zip API and then add a simple facade in order to expose the XS API
