### ISSUE TITLE
[Sample] xsodata-simple public schema missing

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#694]
**Describe the bug**
`xsodata-simple` sample does not work as expected. Schema `PUBLIC` is missing so the table is not created and the xsodata service is not activated

> What version of the XSK are you using?
0.9.2

**To Reproduce**
1. Import `xsodata-simple` sample
2. Click `Publish`
3. See in the logs that public schema is missing

I tried to create `PUBLIC.hdbschema` but the log shows the following:
```java
c.s.x.h.d.s.m.IXSKSchemaManagerService - Synchronized a new HDB Schema file [xsodata-simple::PUBLIC] from location: /xsodata-simple/PUBLIC.hdbschema
c.s.x.h.d.p.h.HDBSchemaDropProcessor - Processing Drop Schema: PUBLIC
c.s.x.h.d.p.h.HDBSchemaDropProcessor - Schema [PUBLIC] does not exists during the drop process
c.s.x.h.d.p.h.HDBSchemaCreateProcessor - Processing Create Schema: PUBLIC
c.s.x.hdb.ds.facade.XSKHDBCoreFacade - CREATE SCHEMA "PUBLIC"
c.s.x.hdb.ds.facade.XSKHDBCoreFacade - SAP DBTech JDBC: [362]: invalid schema name: PUBLIC: line 1 col 15 (at pos 14)
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [362]: invalid schema name: PUBLIC: line 1 col 15 (at pos 14)
```

**Expected behavior**
Sample works upon publishing

**Additional context**
SAP HANA Cloud trial environment version 4.00.000.00.1632216107

**Comment by aihanrashidov** [comment]
The sample works fine with a schema different than `PUBLIC` for `HANA` DB. When trying to create a `PUBLIC` schema on the `HANA` DB the process fails as the `PUBLIC` schema is a special schema keeping synonyms and the user has no privileges using it.
