### ISSUE TITLE
[Parsers] Move HDBDD Parser in-memory state to DB

### ISSUE THREAD

**Issue by BorisNen** [SAP/xsk#715]
The XSKHdbddParser keeps the state of the dependency tree as a map called dependencyStructure.

Problems:
1. If any part of the parsing process fails, the hash of the files might be saved to XSK_DATA_STRUCTURE and it will never be called again.
2. The state is not wiped during Unpublish.
3. The state is lost when XSK is stopped, which requires the project to be published again.

Proposed solution:
1. Move the dependency tree logic to the database and link it to the file metadata in XSK_DATA_STRUCTURE.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
