### ISSUE TITLE
[Migration] There is a hardcoded Neo SDK tunnel host port

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#718]
Currently, there is a hardcoded port `30015` used for connecting to the database. This is an issue if parallel migrations are executed as in this case there would be several open Neo SDK tunnels and they would have different localhost ports. For example, one tunnel could be open on `localhost:30015`, another could be `localhost:30115`, etc. The fix for that issue would be to store the host and port returned by the open tunnel command, and use that instead of a hardcoded host:port.

**Comment by tdermendjiev** [comment]
Fixed by https://github.com/dirigiblelabs/xsk-ide-migration/commit/a402195a02088a242251bfaa2278db12aa3695da
