### ISSUE TITLE
[Migration] Provide a way for users to select users, group and container for the hdi file

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#720]
We should add a new section in the migration perspective in order to enable users to provide us with `users` (array of user names), `group`, and `container` for the hdi file. The hdi file currently sets the `users` array to a provided `HANA_USERNAME` configuration property or to `DBADMIN` if there is no config provided. The `group` and `container` are set to be the project name:
```javascript
const hdi = { 
     configuration: `/${projectName}/${hdiConfigPath}`, 
     users: [defaultHanaUser], 
     group: projectName, 
     container: projectName, 
     deploy: deployables, 
     undeploy: [] 
}; 
```

An important limitation for the `group` and `container` properties is that they have the following requirement for their content: `"A"-"Z", "0"-"9", and "_", and the first character cannot be "_"` This should be validated on the frontend side.

Related to: https://github.com/SAP/xsk/issues/706

**Comment by dpanayotov** [comment]
dependency for
- #1059

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
