### ISSUE TITLE
[Migration] Create a test package on the HANA 2 instance and update the migration tests

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#722]
Currently, we have a test for migrating a simple project from a HANA 1 instance. We should add this project to the HANA 2 instance and create a delivery unit for it. After that, the current test should be extended to migrate this project and assert its content is ok.

**Comment by Fluctuationqt** [comment]
The feature is implemented and disabled, the test credentials do not have access to the Hana 2 Delivery Unit and migrations will get stuck.

**Comment by dpanayotov** [comment]
depends on 
- #725
