### ISSUE TITLE
[Migration] Update the project used for testing the migration to include a calculation view

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#723]
Currently, we are running a test performing a migration of a simple XS application. We should extend this app to have a calculation view and change the test to assert the calculation view is transferred correctly and the `hdi` and `hdiconfig` files are generated.

**Comment by ThuF** [comment]
@vmutafov, @Fluctuationqt I'm moving back this issue to **In Progress**, as there is no linked PR that closes it.

**Comment by vmutafov** [comment]
@Fluctuationqt let's have a meeting to discuss how we would test the HDI-related modifications. I've added a simple calculation view in the test project but we should update some parts of the integration tests.
