### ISSUE TITLE
[Migration] We should state what permissions should each user we use in the migration have

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#725]
Currently, we do not state what permissions should the HANA and Neo users have in order to execute the migration successfully. We should check and list the exact permissions needed and also state we use the Neo SDK open tunnel command.

**Comment by ThuF** [comment]
- How to create a **Delivery Unit** is already documented here: https://www.xsk.io/cheatsheet/delivery-unit/
- The **Database User** setup page (focused on HANA Cloud) is available here: https://www.xsk.io/setup/database-user/

@vmutafov maybe we should add in the **Database User** section about Neo prerequisites.

**Comment by dpanayotov** [comment]
HANA User must have the following system privilege: `REPO.MAINTAIN_DELIVERY_UNITS`. This can be assigned explicitly or through the role `sap.hana.xs.lm.roles::Administrator`.

I'll prepare a change to xsk.io to document this

**Comment by dpanayotov** [comment]
fixed with #1509
