### ISSUE TITLE
[Tests] Integration Tests: Difficulty running integration tests in forks.

### ISSUE THREAD

**Issue by Fluctuationqt** [SAP/xsk#730]
When forking the repo the integration tests will execute in the fork's nightly, but the secrets are not forked. This might be an issue for a contributor. Some of those tests require credentials or other data from github secrets. Should they be [skipped/documented for contributors] because data to run the tests has silently gone missing?

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
