### ISSUE TITLE
[Customer] - GSTR: Invalid name of function or procedure

### ISSUE THREAD

**Issue by LiliyaLazarova** [SAP/xsk#733]
During the testing of customer's project GSTR the following errors popped up:

![image](https://user-images.githubusercontent.com/20951516/139639186-177779cf-9d48-4073-9b3b-d858a07fbf58.png)

**Comment by ThuF** [comment]
Moving back to **To do** as there was no progress recently.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
