### ISSUE TITLE
[Customer] - GSTR: Parameters are not allowed for entity XXX as it is not a calculation or analytical view.

### ISSUE THREAD

**Issue by LiliyaLazarova** [SAP/xsk#734]
During the testing of GSTR customer project the following problem has been listed:
Parameters are not allowed for entity sap.slh.dcs.gstrmdc/CV_USER_BP_FORM_ACTIVITY.calculationview as it is not a calculation or analytical view.

> GSTR: Parameters are not allowed for entity sap.slh.dcs.gstrmdc/CV_USER_BP_FORM_ACTIVITY.calculationview as it is not a calculation or analytical view.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
