### ISSUE TITLE
[Integration tests] Environment setup

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#750]
## Preparation
- [x] 1. Prepare k8s cluster for testing
- [x] 2. Prepare HANA Cloud instance
- [x] 3. Ensure configuration can be passed through GitHub action

## Deployment
1. Deploy sap/xsk docker image to Kubernetes or Kyma cluster in a separate namespace
2. The deployment should be configured to connect to SAP HANA Cloud Instance.
3. The security configuration should be in such way, that it should be possible to invoke Dirigible REST APIs remotely (e.g. through the client credentials OAuth 2.0 flow).

## Cleanup
1. Remove namespace and all resources in it

## Acceptance criteria
- [x] There's an action that deploys XSK on a k8s cluster
- [ ] XSK APIs can be called from the action

**Comment by krasimirdermendzhiev** [comment]
Preparation
1. Created Kyma cluster on BTP
2. Created HANA Cloud instance

**Comment by ThuF** [comment]
Acceptance criteria were met. The remaining `XSK APIs can be called from the action` would be tracked in a separate [issue](https://github.com/SAP/xsk/issues/882).
