### ISSUE TITLE
[Logging] Configuration credentials logged

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#752]
**Describe the bug**
Upon startup the whole configuration is logged on INFO level. This includes credentials for connecting to HANA Cloud instance

> What version of the XSK are you using?
0.9.3

**To Reproduce**
1. Start XSK
2. See credentials in logs

**Expected behavior**
Sensitive data is not logged

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1571

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1570, will be available with the next release of Eclipse Dirigible.
