### ISSUE TITLE
Adopt latest monaco version

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#759]
The current monaco editor is with an old version (updated 2y ago) - https://github.com/dirigiblelabs/ide-monaco/tree/master/ide-monaco/monaco-editor

We need to adopt the latest changes from https://github.com/microsoft/monaco-editor

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1265

**Comment by ThuF** [comment]
Fixed in Eclipse Dirigible with: https://github.com/eclipse/dirigible/pull/1301

Will be adopted in XSK with the next Eclipse Dirigible release.
