### ISSUE TITLE
[IDE] No option to create a .xsaccess file

### ISSUE THREAD

**Issue by ivanvolkoff** [SAP/xsk#765]
Currently, there's no option to create a .`xsaccess` file through right click --> New--> filetype. None of the options available through this menu creates a `.xsaccess` file.

<img width="359" alt="Screenshot 2021-11-11 at 9 55 45" src="https://user-images.githubusercontent.com/61655573/141260122-576c5697-1a42-4e2b-81e1-9fe72c4e0770.png">

**Expected behavior**
Such option should be available.

**Comment by dimitarquanterall** [comment]
Is this really needed as there is no peculiar .xsaccess editor and these files are just JSON containing ones? 
.xsaccess file can be created by just using New -> File and providing ".xsaccess" as a name.

**Comment by dimitarquanterall** [comment]
Please, assign to me.
