### ISSUE TITLE
[Migration] Support 2FA codes input

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#767]
Currently, there is an issue if you have enabled 2FA for your SAP user and want to perform a migration. 
The problem is due to the asynchronous nature of how we perform the migration using a Flowable process. Suppose the user appends his 2FA code after his Neo password, because we collect the user credentials in one of the first steps of the migration, there is a chance some Neo SDK commands would be executed with a "password:2FA-code" pair where the 2FA code could be expired.
The fix for this problem could be by creating a 2FA input field on each step in the migration where it would be needed.

**Comment by vmutafov** [comment]
Related to: https://github.com/SAP/xsk/issues/625

**Comment by ThuF** [comment]
I'm reopening the issue, as it seems that the **main** branch in the **xsk** repository was not updated with the latest content committed in the **xsk-ide-migration** repository, regarding the 2FA codes (JWT):

- https://github.com/dirigiblelabs/xsk-ide-migration/blob/07602383f483003aabab8670f88dc53c97395101/ide-migration/server/migration/api/migration-rest-api.js#L19-L23

- https://github.com/SAP/xsk/blob/68b14fade62dcde009aa974ca61ae0e723250689/modules/ide/ide-migration/src/main/resources/META-INF/dirigible/ide-migration/server/migration/api/migration-rest-api.js#L29

**Comment by ThuF** [comment]
Fixed with: https://github.com/SAP/xsk/pull/822
