### ISSUE TITLE
[Epic] Integration Tests

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#77]
Step executing **integration test** scenarios to be added to the `Build` and `Pull Request` GitHub Actions. The integration test should perform the following actions:
1. Deploy `sap/xsk` docker image to `Kubernetes` or `Kyma` cluster.
1. Invoke Dirigible REST APIs in order to `Import` and `Publish` the `*.zip` samples or designated integration test projects.
1. Invoke sample's REST APIs in order to determine whether the test passed successfully or not.
    - **Note:** the integration test should be time tolerant (e.g. 1-2 min.), so that all Dirigible synchronizers should have enough time to pass successfully.
1. Invoke sample's REST APIs to **unpublish** and **delete** the created artefacts in the `SAP HANA Cloud` instance.

Failure case:
If there's failure (in the test or caused by a synchronizer), the logs should be dumped in the action for debugging purposes. 

Issues in epic
- [ ] #750 
- [x] #163 
- [x] #1059
- [x] #458
- [x] #604

**Comment by dpanayotov** [comment]
Consider parallel executions

**Comment by krasimirdermendzhiev** [comment]
Maybe if we run consecutively - when stop the previous to start new one.

**Comment by krasimirdermendzhiev** [comment]
I'm thinking to cache some steps if we can try to use actions/cache@v2 for steps - Setup sapmachine JDK 11, Download sapmachine JDK 11

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
