### ISSUE TITLE
[IDE] Option to publish/unpublish file selection

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#774]
### Story
1. As a developer, I'd like to select a single file for publishing, so that I don't have to publish all files in a directory in case they are not ready for publishing.
2. As a developer, I'd like to select multiple files for publishing, so that I don't have to publish all files in a directory in case they are not ready for publishing.

### Acceptance Criteria
- [ ] When I right-click a file, there should be an option to `Publish` which when pressed publishes the file (same behavior as if file were in a directory and I click publish on the directory)
- [ ] When I select multiple files and right-click, there should be an option `Publish selected` which when pressed publishes the selected files (same behavior as if the files were in a directory and I click publish on the directory)

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1281

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/commit/7053172c0b6172c0800b16c5b008187f78dbba3a, will be available with the next Eclipse Dirigible release.
