### ISSUE TITLE
[UI] Research for new layout engine

### ISSUE THREAD

**Issue by StanZGenchev** [SAP/xsk#775]
Currently, XSK uses a very old version GoldenLayout for a layout engine and sand-boxing different views. Older versions have some limitations, add some unwanted functionality to XSK and will stop working in future browser versions. Newer GoldenLayout versions are too buggy to be used. Research for possible alternatives.

Related to Dirigible issue https://github.com/eclipse/dirigible/issues/1283

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
