### ISSUE TITLE
[Migration] Automatically create hdbsynonym in HDI container for external artifacts

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#792]
### Background
You have an hdbtable in a schema in HANA Cloud and you want to build a calculation view that uses this table.
The calculationview lives in the HDI container, but the table is outside of it.
You need to create an hdbsynonym pointing to the table in the hdi container so that it can be resolved inside the container. Even if there is a public synonym it's not enough, as the container doesn't see the public synonyms

### Target
Create `hdbsynonym` for all tables/views/procedures that are used by the calculation views or hdbtablefunctions and are not in the HDI container.
**Note** Synonym name must remain the same as the original artifact so that minimal changes are needed in views/functions that are referencing them.

 Example for hdbsynonym:

 ```json
 {
  "MY_APP.DATA::data.User": {
    "target": {
      "object": "MY_APP.DATA::data.User",
      "schema": "MY_SCHEMA"
    }
  },
  "MY_APP.DATA::data.Address": {
    "target": {
      "object": "MY_APP.DATA::data.Address",
      "schema": "MY_SCHEMA"
    }
  }
}
 ```

**Note: This must be done by the migration tool and all changes need to be reflected in the tree after finishing the migration and not somehow in the background.**
**Note: File modifications are done in a temporary directory that is later on transferred** TBD directory name and interface for interaction

**Comment by dpanayotov** [comment]
To be covered by #872

**Comment by ThuF** [comment]
Duplicated by #872
