### ISSUE TITLE
Automatically create synonyms for artifacts inside the HDI container, so they are reachable without id change

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#797]
### Background
Example - a view is referenced in an odata file via `PACKAGE1.PACKAGE2::VIEWNAME` after it is moved to the hdi container a synonym should be created 

Similar to #792  but instead of creating synonym in the container for external artifacts, create synonym for the artifacts in the container.

### Target
For all resources created in the HDI container, create a public synonym pointing to the resource in the hdi container.
```
"PACKAGE1.PACKAGE2::VIEWNAME": {
		"target": {
			"object": "VIEWNAME",
			"schema": "HDICONTAINERNAME"
		}
	}
```

**Comment by dpanayotov** [comment]
To be covered by #872

**Comment by ThuF** [comment]
Duplicated by #872
