### ISSUE TITLE
[Migration] Use WebSockets instead of HTTP polling for Migration results

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#798]
Currently, the migration tool's frontend makes HTTP requests each second while the Flowable process is being executed. These requests are handled by the migration REST API and check at what step the Flowable process is. Although this is currently working well enough, we should start using WebSockets as they would be more optimal. 

The Dirigible already has an [API for WebSockets](https://www.dirigible.io/api/net/websocket/) and we should start using it.
We should consider thoroughly the cases we may need to reconnect the sockets. A possible improvement would be to start using [this](https://github.com/joewalnes/reconnecting-websocket) in the Dirigible.

**Comment by ThuF** [comment]
Blocked by the WebSockets issue:
- https://github.com/SAP/xsk/issues/595

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
