### ISSUE TITLE
[Migration] Refactor the way we handle the delivery units' content

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#799]
Currently, we use the HANA REST APIs to fetch each delivery unit and its files. Although this works well enough, for now, we may have problems when migrating big XS applications as we get its content, keep it in the memory, and at a later time iterate those files in order to upload them in the Dirigible. 

We should change this approach and have a separate loop task in Flowable for handling each delivery unit file - getting its content, doing some additional work (if necessary, e.g. calculation views), and saving it in XSK. 
This would allow the JVM GC to collect any big files sooner and also give us the ability to more granularly retry the Flowable task in case of any errors.

**Comment by dpanayotov** [comment]
fixed with https://github.com/dirigiblelabs/xsk-ide-migration/pull/21
