### ISSUE TITLE
[Migration] Modifications to be reflected as git commits

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#803]
Each step of the migration tool that modifies file contents should commit the changes in a local git repository that is in the migration folder

Related to #738

**Comment by ThuF** [comment]
@vmutafov, @tdermendjiev moving back to **In Progress** as there was no PR to review.

**Comment by vmutafov** [comment]
Implemented in the dirigiblelabs ide-migration repo, to be merged into XSK.
