### ISSUE TITLE
[Migration] Keep track of migrated DUs

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#807]
### Background
Related to #806 
If a migration process is migrating multiple DUs at the same time, some might fail. When a user goes to the migration wizard again to migrate the remaining it would be helpful to see which ones have been successfully migrated.

### Target
1. Store the result of the migration process per DU.
2. In the DU list show indication which DUs have already been migrated. The list may be split into two section - `Migrated`, `Not migrated`, but you'd be able to select from either subsection
3. Repeated migration of the same DU should be possible

**Comment by ThuF** [comment]
@vmutafov, @ivanvolkoff I'm moving back this issue to **In Progress**, as there is no linked PR that closes it.

**Comment by vmutafov** [comment]
Implemented in the dirigiblelabs ide-migration repo, to be merged into XSK.
