### ISSUE TITLE
[Releng] Separate helm charts 

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#808]
Create separate helm chart for kpack and xsk deployment.

**Comment by krasimirdermendzhiev** [comment]
- Update XSK helm chart
https://www.xsk.io/setup/helm/#setup-on-kyma

- Added new XSK kpack helm chart 
https://www.xsk.io/setup/helm/#kpack-setup

- Added release step for XSK kpack
`helm package xsk-kpack`

**Comment by ThuF** [comment]
Separation of Helm Charts is successful. All details could be found at: https://www.xsk.io/setup/helm/
