### ISSUE TITLE
[Migration] Research if HANA 2.0 XS apps with an HDI need special handling

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#818]
Currently, the HANA 2.0 instances allow users to create HDI files. When migrating XS applications, we implicitly assume there is no HDI file. 

The goal of this issue is to check if there is a need for generating a new HDI file or we could probably reuse the already existing one in the application.

**Comment by ThuF** [comment]
As the `.hdi` file was introduced by **XSK**, there shouldn't be any existing `.hdi` files in the HANA 1.x/2.x projects. @vmutafov could we close this issue, or there is more context to it?

**Comment by vmutafov** [comment]
I'll close this issue. I opened it because I thought in the beginning that`.hdi` files are something coming from the XS apps. I forgot to close it when I found out the `.hdi` files are our own files. Sorry for the inconvenience
