### ISSUE TITLE
[XSOData] Entity definition cannot use synonyms

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#823]
When you have schema different form the user's/default one in which your tables are and you want to have OData service exposing them you will need to use synonyms, but currently this is not allowed by the OData framework.

Logic in XSKODataParser should be changed to:
1. accept synonyms as entity 
2. take the synonym's target object and use it for further checks (e.g. to check whether it is a view or table)

The same should be done also in OData2ODataXTransformer (Dirigible)

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1295

**Comment by MarinHadzhiev** [comment]
Sample code for getting synonym's target object

```java
try (Connection connection = dataSource.getConnection()) {
				PreparedStatement prepareStatement = connection.prepareStatement(
						"SELECT * FROM \"SYS\".\"SYNONYMS\" WHERE \"SYNONYM_NAME\" = ? AND \"SCHEMA_NAME\" = ?");
    prepareStatement.setString(1, synonymArtifact.getName());
    prepareStatement.setString(2, synonymArtifact.getSchema());
    
    try (ResultSet result = prepareStatement.executeQuery()) {
	    if (result.next()) {
		    String type = result.getString("OBJECT_TYPE");
		    if (dbTypes.contains(type)) {
			    String name = result.getString("OBJECT_NAME");
			    String schema = result.getString("OBJECT_SCHEMA");
			    return new DBArtifact(name, type, schema);
		    }
	    }
    }
} catch (SQLException e) {
   throw new RuntimeException("Failed to get details for synonym - " + synonymArtifact.getName() , e);
}
