### ISSUE TITLE
[XSOData] Searching for DB artefact should be only in default user schema

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#824]
When OData service is defined the logic behind is checking whether the related DB artefacts exist, this check should be done only in the default schema and in the PUBLIC schema in case the artefact is a synonym.

related classes: XSKODataParser in XSK and DBMetadataUtil in Dirigible

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1296
