### ISSUE TITLE
[DB Perspective] "command + x" is not executing all or selected sql statements

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#852]
With version 0.11.0 "command + x" / "ctrl + x" combination is not executing the selected SQL statement but instead is working as "cut" command, so we need to change the "execute" key to F8 as it is in the HANA Studio

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1308

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1318, will be available with the next release of Eclipse Dirigible.

The change of key binding to be tracked in separate issue: #865
