### ISSUE TITLE
[Migration] Refactor the migration perspective's API calls

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#862]
Currently, we call the migrations backend for more data than we have thought initially. These calls however are directly in the ng controllers and are not using the async/await syntax. This leads to hard maintenance, possible bugs, duplicated code, and it gets hard to track what exactly is called from the backend. 

We should extract all API calls into one or more ng services in order to handle the issues listed above.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
