### ISSUE TITLE
[IDE] Database - Change Execute SQL Command Key Binding

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#865]
In #852 it was proposed to change the `execute` SQL command key binding from `ctrl + x`/`command + x`to `F8` as it is in the `HANA Studio`.

Related to: https://github.com/SAP/xsk/issues/852

**Comment by ThuF** [comment]
Other proposals for the key binding are welcome!

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
