### ISSUE TITLE
[Migration] Improve synonym generation

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#872]
### Target
1. Create `*.hdbpublicsynonym `with all artifacts that are being created
2. Create `*.hdbsyonym` with the synonyms that the HDI container needs (phase 1 - tables, views and tabletype)

#### Details
This means that the migration procedure needs to process the artifacts and create these 2 new files in the project tree.
There needs to be processor for these 2 files
The code that currently creates public synonyms for specific hdb artifacts needs to be removed as this will be handled by the synonym synchronizers.

Related to #792 and #797

**Comment by ThuF** [comment]
@dimitarquanterall please write a comment here, so I could assign you to the issue.

**Comment by dimitarquanterall** [comment]
Please, assign this to me
