### ISSUE TITLE
[XSOData] Add support for all HANA Cloud data types

### ISSUE THREAD

**Issue by MarinHadzhiev** [SAP/xsk#875]
Data types - NCLOB, CLOB, TEXT, BINTEXT, ALPHANUM are not supported by the OData framework.

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1329

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1332, will be available with the next release of Eclipse Dirigible.
