### ISSUE TITLE
[Integration tests] WebIDE test

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#882]
It should be possible introduce a new step after [Wait XSK Kyma Startup](https://github.com/SAP/xsk/blob/main/.github/workflows/nightly.yml#L202-L208) in the nightly build, to migrate project containing XS specific artefacts like:
- `*.xsjs`
- `*.hdbtable`
- `*.calculationview`
- etc.

**Note:** To be able to execute the test multiple times, it should be possible to `Unpublish` (drop) the database artefacts like `*.hdbtable`, `*.hdi`, `*.hdbdd`, etc.

Related to:
- https://github.com/SAP/xsk/issues/750
- https://github.com/SAP/xsk/issues/540

1. Create Selenium Test to:
    - `Login`
    - `Open migration perspective`
    - `Migrate from ZIP`
    - `Import products sample zip` --> https://github.com/sap/xsk/releases/download/<version>/products.zip --> PRODUCTS_XSC.zip
    - `Execute migration`
    - `Validate content is as expected` --> compare with downloaded products.zip
    
    > As these steps seems like a lot of effort to be implemented with commands in the GitHub action (and will be also hard to maintain) it would be best to be implemented as an external program e.g. Node.js/Dirigible app.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
