### ISSUE TITLE
[Migration] Analytic Privileges - Artefact processing

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#891]
### Background
In HANA on Neo, some analytic privileges had checks that used the `SESSION_USER` session variable. 
In HANA Cloud this session user is the technical user with which the connection is established. As XSK will set the `APPLICATIONUSER` as session variable we should adjust the SQLs to use that instead.

#### Content processing
1. When migrating `.analyticprivilege` files, check them for usage of `SESSION_USER` and replace all occurrences with `SESSION_CONTEXT(APPLICATIONUSER)`
2. Adjust each `modelUri` so that it's just the name of the calculationview
3. Process the SQL and replace references to other calculation views such as `"_SYS_BIC"."APP.VIEWS/CALCVIEW"` with just `CALCVIEW`

#### Deployment
1. Add the analyticprivilege file to the artifacts that need to be deployed in the `.hdi` file
2. Make sure that the `hdiconfig` file has the `com.sap.hana.di.analyticprivilege` plugin enabled for `analyticprivilege` and for `hdbanalyticprivilege` file types

#### Related to:
- https://github.com/SAP/xsk/issues/902
- https://github.com/SAP/xsk/issues/906
- https://github.com/SAP/xsk/issues/791

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/902

**Comment by aihanrashidov** [comment]
Resolved by #1020
