### ISSUE TITLE
[Research] Check Kyma 2.0

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#894]
Research the new Kyma 2.0 release.

- [x] Test XSK Deployment
- [x] Test connectivity

**Comment by krasimirdermendzhiev** [comment]
# Kyma 2.0

## No longer support the following authentication and authorization components

* API Server Proxy
* Console Backend Service
* Dex
* IAM Kubeconfig Service
* Permission Controller

## [API Exposure](https://kyma-project.io/blog/2021/12/7/release-notes-20#exposing-workloads-on-custom-domains)

* Exposing workloads on custom domains. Kyma 2.0 allows you to expose Istio workloads using custom, user-managed domains.

## [Application Connectivity](https://kyma-project.io/blog/2021/12/7/release-notes-20#application-connectivity)

* New way to reach registered services. Kyma 2.0 brings some fresh air to the Application Connectivity area.

* [Application Connectivity improvements](https://kyma-project.io/blog/2021/12/7/release-notes-20#application-connectivity-improvements)

## [CLI](https://kyma-project.io/blog/2021/12/7/release-notes-20#cli)

* Switch from Minikube to k3d
* Revamped way of installation
* Values instead of configuration overrides
* The kyma test command deprecated
* The kyma console command replaced with kyma dashboard

## [Eventing](https://kyma-project.io/blog/2021/12/7/release-notes-20#eventing)

* NATS Operator replaced with NATS Helm chart

## [Kyma Dashboard](https://kyma-project.io/blog/2021/12/7/release-notes-20#kyma-dashboard)

* Kyma Console replaced with new technology
* Kyma Dashboard features

## With the 2.0 release, Kyma does not expose Grafana, Kiali, and Jaeger UIs by default. After the upgrade, for each service, you can set up an identity provider of your choice.

## New resources views

* Service Accounts
* Cluster Overview > Nodes
* Jobs
* Cron Jobs
* Stateful Sets
* Daemon Sets
* Gateways
* Issuers
* Certificates
* DNS Providers
* DNS Entries

## Easier resource creation

* Roles
* Role Bindings
* Service Accounts
* Deployment
* Cron Jobs
* Jobs
* Config Maps
* Secrets
* Issuers
* Certificates
* DNS Providers
* DNS Entries
* Replica Sets

All Dashboards are accessible trough <https://dashboard.kyma.cloud.sap>

## Connect your cluster

1. You need to paste or drag kubeconfig file to connect your cluster.

2. Privacy Options - ou can choose where to store your cluster configuration. Based on your kubeconfig type, we recommend the pre-selected storage mode. You can choose whatever you prefer for convenience and security. None of the options stores information on the server.

* Local storage - Cluster data is persisted between browser reloads.

* Session Storage - Cluster data is cleared when the page session end.

* In memory: Cluster data is cleared when you leave or refresh the page.

## Cluster Overview

1. Cluster overview section - you can see versions for kubernetes and Kyma, API server address, Storage Type.

2. Nodes section - you see your nodes

3. Message section - you can see all messages for your cluster.

## Namespaces

1. Columns - you can see names, created, labels, status.

## Events

- Columns - name, type, message, involved object, source, count, last seen

## Integration

- Applications

* Methods for creating applcation - Simple, Advanced, YAML

- Cluster Addons - look the same.

## Configuration - the old Administration become Configuration

- Cluster Roles

* Columns - Name, Created, Labels, Alerts, Configurations

- Cluster Role Bindings

* Columns - Name, Created, Labels, Role reference, Subjects, Alerts, Configurations

- Custom Resource Definitions

* Columns - Name, Created, Labels, Scope, Categories, Alerts, Configurations

## [Observability](https://kyma-project.io/blog/2021/12/7/release-notes-20#observability)

* Improved security for logs in Kyma Dashboard
* Containerd support
* Prometheus mTLS
* Observability services updated

1. Grafana

2. Kiali

3. Tracing

## [Security](https://kyma-project.io/blog/2021/12/7/release-notes-20#security)

* Native Kubernetes authentication in Kyma

  1. OpenID Connect tokens
  1. Role Based Access Control (RBAC)

* Full list of removed authentication and authorization components:
  1. API Server Proxy
  2. Console Backend Service
  3. Dex
  4. IAM Kubeconfig Service
  5. Permission Controller  

* Ory Oathkeeper without Dex

## [Serverless](https://kyma-project.io/blog/2021/12/7/release-notes-20#serverless)

* Support for Python 3.8 deprecated - Python 3.9 available

## [Service Management](https://kyma-project.io/blog/2021/12/7/release-notes-20#service-management)

* Service Catalog deprecation update

    These are the examples of service operators provided by hyperscale cloud providers that you can use:
    
    Google Cloud
    Azure
    AWS
    
    The Service Catalog removal will also affect Application Connectivity in Kyma. Service Catalog objects will not be used anymore, and both ServiceInstances and ServiceBindings will not be required.

Recap
At this point XSK is deployed normally. We will check periodically for any new changes.

**Comment by rdimitrov4** [comment]
To add a new Cloud Connector administrator in an existing Kyma Cluster we must use: 
`cluster-admin(CR)` Role;
`app=kyma` and `type=admin` Labels;
`Kind: User` and the `user's email` for Subject;
when creating the `Cluster Role Binding`
