### ISSUE TITLE
[Migration] Analytic Privileges - Revert #802

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#897]
### Background
#802 was introduced in an effort to handle analytic privileges ourselves through XSOData (#869) and not leave all the processing to HANA Cloud.
A new design has been discussed and approved which covers more scenarios but requires us to revert #802 and leave the checks to HANA Cloud. 

### Target
Revert the changes from #802  so that the tags remain as before

**Comment by ThuF** [comment]
The fix is available in dirigiblelabs organization, to be merged in XSK.
