### ISSUE TITLE
[Analytic Privileges] Set APPLICATIONUSER in db session

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#898]
### Background
In APs for row based filtering so far the SESSION_USER was used which is the logged in user. In HANA Cloud this resolves to the technical user with which the connection is established. This means that checks should be adjusted to use a different session variable. HANA Cloud defines `APPLICATIONUSER` in the [SAP Help Portal](https://help.sap.com/viewer/c1d3f60099654ecfb3fe36ac93c121bb/2021_3_QRC/en-US/a16678c085bf475f832c10b2629f3997.html)

### Target
When obtaining a connection use `setClientInfo` with key `APPLICATIONUSER` and value to be the name of the logged in user.
If no user is logged in set the value to `ANONYMOUS`.
This needs to work with both `$.db.getConnection()` and `$.hdb.getConnection()`.
See the Java api for [setClientInfo](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setClientInfo(java.lang.String,%20java.lang.String))

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1375

**Comment by ThuF** [comment]
I’m not sure, if the merged [PR](https://github.com/eclipse/dirigible/pull/1376) in Eclipse Dirigible is enough to handle also the database connectivity via OData, which is by the way the most common scenario for the consumption of the analytical privileges. As of now the `clientInfo()` is set only in the [DatabaseFacade](https://github.com/eclipse/dirigible/blob/master/api/api-facade/api-database/src/main/java/org/eclipse/dirigible/api/v3/db/DatabaseFacade.java#L636-L649) which will cover the `XSJS` scenario only. Maybe a better approach will be to add this functionality inside the [DatabaseModule](https://github.com/eclipse/dirigible/blob/master/modules/database/database-api/src/main/java/org/eclipse/dirigible/database/api/DatabaseModule.java#L135-L148) or inside the [WrappedDataSource](https://github.com/eclipse/dirigible/blob/848502fb77b371b244ca2db7fab5636eee7c0671/modules/database/database-api/src/main/java/org/eclipse/dirigible/database/api/wrappers/WrappedDataSource.java#L120-L155).

So I’m reopening the issue for further development.

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1425, will be available with the next version of Eclipse Dirigible.
