### ISSUE TITLE
[API] Allow configuration for on-premise mail server

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#900]
### Story
As an administrator I want to configure on-premise mail server so that the XS application can send mails using it.

### User flow
1. Create destination of `Type=Mail` in [SAP BTP Destination service UI](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/6442cb4f8b0f41178abce14c35f5def4.html) and set `Proxy Type` to `OnPremise`
1.1. See [example](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/3a2d57580d474da6960a644462a92861.html#loio3a2d57580d474da6960a644462a92861__mail_onpremise)
1.2. The host and port need to be the virtual host and port configured in SCC. See example from [this blog](https://blogs.sap.com/2020/01/08/cloud-integration-connect-cpi-with-your-on-premise-mail-server/)
2. Deploy Connectivity Proxy in cluster ( see #894)
3. Configure XSK to use this mail server via the destination (see #899)

### Implementation
_See how to configure SMTP transport from [here](https://blogs.sap.com/2021/05/07/connect-to-an-on-premise-mail-server-from-sap-btp-cloud-foundry/)
See implementation of ConnectivitySocks5ProxySocket from the documentation [here](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/cd1583775afa43f0bb9ec69d9dbcc880.html#loiocd1583775afa43f0bb9ec69d9dbcc880__example)
`getProxyAddress` should be configured to be the address of the Connectivity Proxy deployed on the Kyma cluster_

**EDIT: Above is not valid for Kyma**
In Kyma, the connectivity-proxy does not require these settings and can be simply configured with `mail.smtp.socks.host` and `mail.smtp.socks.port`

Most of the implementation is in [eclipse/dirigible MailFacade](https://github.com/eclipse/dirigible/blob/master/api/api-facade/api-mail/src/main/java/org/eclipse/dirigible/api/v3/mail/MailFacade.java)

depends on #899

**Comment by dpanayotov** [comment]
blocked as socks5 is disabled in connectivity-proxy deployment managed by Kyma

**Comment by dpanayotov** [comment]
fix expected to be part of Kyma 2.1 https://github.com/kyma-project/kyma/milestone/373

**Comment by d-velev** [comment]
As Istio is blocking SOCKS5 traffic, a workaround is to patch the connectivity proxy's stateful set as so: `kubectl -n kyma-system patch statefulset connectivity-proxy -p '{"spec": {"template":{"metadata":{"annotations":{"traffic.sidecar.istio.io/excludeInboundPorts": "20004"}}}} }'`

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1718

**Comment by d-velev** [comment]
Reopening since scenario doesn't work on customer's cluster

**Comment by dpanayotov** [comment]
Functionality is working on XSK side. Configuration in SCC to be revised
