### ISSUE TITLE
[Migration] Analytic Privileges - Replace SESSION_USER in SQL

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#906]
### Target
Process the following artefacts so that usage of `SESSION_USER` are replace with `SESISON_CONTEXT('APPLICATIONUSER')`

 - [ ] xsjs
 - [ ] xsjslib
 - [ ] hdbprocedure
 - [ ] hdbtablefunction

**Comment by ThuF** [comment]
The [workspace](https://www.dirigible.io/api/platform/workspace/) API could be used to process files.
