### ISSUE TITLE
[Samples] Run SHINE Application

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#907]
Run the [SHINE](https://github.com/SAP-samples/hana-shine) sample application on XSK.
- [ ] list processing of which artefacts is not supported
- [ ] list compatibility issues
- [ ] list manual changes required

**Comment by aihanrashidov** [comment]
Upon running the application in the XSK environment the first errors encountered were due to the `.hdbdd` artefacts not being parsed and processed properly.

Related issues:
- #1073 
- #908
- #910
- #912

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
