### ISSUE TITLE
[HDBDD] SearchIndex are not processed

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#908]
Error messages in the `Problems` view:

- `@SearchIndex.text.enabled - no viable alternative at input '@SearchIndex.text.'`
- `@SearchIndex.fuzzy.enabled - no viable alternative at input '@SearchIndex.fuzzy.'`

Sample definition:

```
namespace app.test.abcd;
@Schema: 'ABCD' 

context QWERTY {
    type ty_company     : String(4); 
    type ty_assetNo     : String(12);
    type ty_assetSubNo  : String(4);

    Entity ENTITY1 {
        key COL1                    : ty_company;
        COL2                        : ty_assetNo;
        @SearchIndex.text.enabled   : true        
        @SearchIndex.fuzzy.enabled  : true            
        COL3                        : ty_assetSubNo;
};
```

**Comment by SAtanasovv** [comment]
If we try to speed up the fuzzy search by creating a data structure called ' FUZZY SEARCH INDEX ' , accessing it through the @SearchIndex annotation throws an exception in the HANA Cloud.(Note: FUZZY can be used in SELECT and WHERE without FUZZY SEARCH INDEX ON)

**Comment by dpanayotov** [comment]
related to 
- #390

**Comment by dpanayotov** [comment]
Check if building the create table sql statement as shown [here|https://help.sap.com/viewer/05c9edaee7fe4d28ab3627d0b1583df6/2021_4_QRC/en-US/d2d6cb461d4e4cdd9611f64bacdab1b8.html] works

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1656
