### ISSUE TITLE
[IDE] Copy existing to show prompt

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#919]
### Background
If I copy a directory that already exists I don't get prompt what to do. The process just fails and I get no message what happened. 
If I copy `file.txt` in a directory which contains `file.txt` it'll actually create another file called `file (copy 1).txt`

#### File behavior
When a file is copied to a directory in which the same one exists, a prompt must be shown to the user.
Options should be `Replace`, `Keep both`, `Skip`. There should be a checkbox saying `Apply to all` which must apply the selected operation to all files. (this is similar to the behavior in MacOS)
* If you choose `Replace` it must overwrite only this file. 
  * If `Apply to all` is selected, all conflicting files are replaced and the operation finishes
  * If `Apply to all` is not selected, the operation continues and the dialog must be shown for the next conflicting file
* If you choose `Keep both` it must keep the current behavior where another file called `file (copy 1).txt` is created
  * If `Apply to all` is selected, for all conflicting files another one is created and the operation finishes
  * If `Apply to all` is not selected, the operation continues and the dialog must be shown for the next conflicting file
* If you choose `Skip` this file must be skipped
  * If `Apply to all` is selected, all conflicting files are skipped and the operation finishes
  * If `Apply to all` is not selected, the operation continues and the dialog must be shown for the next conflicting file

#### Directory behavior
When a directory is copied to a directory in which one with the same name exists, a prompt must be shown to the user only if there are conflicting files. Otherwise just merge the two directories.
The behavior should be that for each file the algorithm above must be followed. Essentially it translates to:
1. If file does not exist - copy it
2. If file exists - show dialog from above

**Comment by dpanayotov** [comment]
Issue cloned to https://github.com/eclipse/dirigible/issues/1367

**Comment by dimitarquanterall** [comment]
Please, assign it to me

**Comment by dimitarquanterall** [comment]
Fixed by https://github.com/eclipse/dirigible/pull/1657
The issue may be closed after the PR is merged.

**Comment by dpanayotov** [comment]
fixed with https://github.com/eclipse/dirigible/pull/1657 
Will be part of next adoption of eclipse/dirigible
