### ISSUE TITLE
[Workbench] Add 'hdbti' to new file menu

### ISSUE THREAD

**Issue by StanZGenchev** [SAP/xsk#937]
**Describe the issue**
When a user right clicks on a project or a folder, he should be presented with the option to create a new empty hdbti file.

> Is this issue related to a specific component?

xsk-workspase-menu

Depends on #934 

**Desktop:**
 - OS: macOS 12
 - Browser: Firefox 95
 - Version: XSK 0.12.0

**Comment by ThuF** [comment]
Depends on, as the Build action will fail due to XSK JUnit Tests issues with Eclipse Dirigible version `6.1.12`:
- https://github.com/SAP/xsk/issues/934
