### ISSUE TITLE
[Documentation] Local Setup

### ISSUE THREAD

**Issue by himchev** [SAP/xsk#940]
### Deploy on Tomcat server

- 'export' is a platform specific command so I guess that should be elaborated?
- 'Configure connection to HANA Cloud instance.' - It would've been nice if there was a link to a tutorial or video on how to sign up for a HANA Cloud trial.
- 'Stop the container: docker stop dirigible' - That doesn't seem relevant when deploying on Tomcat server?

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
