### ISSUE TITLE
Keep synchronization state for artifacts

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#961]
This is the second part of:
- #768 

----

Related to https://github.com/eclipse/dirigible/issues/1277 and https://github.com/eclipse/dirigible/issues/1278

XSK needs to keep track of the synchronisation state of each artifact it tries to activate. This will help in troubleshooting and in determining the sequence of activation of artifacts - ie a view can't be activated because the table is in failed state.

Related to https://github.com/eclipse/dirigible/issues/1277 

XSK needs to keep track of the synchronisation state of each artifact it tries to activate. This will help in troubleshooting and in determining the sequence of activation of artifacts - ie a view can't be activated because the table is in failed state.

### Target
- [ ]  .hdbstructure
- [ ]  .hdbti
- [ ]  .xsaccess
- [ ]  .xsapp
- [ ]  .xshttpdest
- [ ]  .xsjob
- [ ]  .xsjs
- [ ]  .xsjslib
- [ ]  .xsodata
- [ ]  .xsprivileges
- [ ]  .xssecurestore

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
