### ISSUE TITLE
[Migration] Error while fetching delivery units

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#970]
**Describe the bug**
When fetching the delivery units a generic error is returned, but in the network tab a response with the partial exception is logged

> What version of the XSK are you using?
latest

**To Reproduce**
1. Start xsk container locally - `docker run ....  dirigiblelabs/xsk:latest`
1. Go to migration perspective
2. Enter BTP credentials
3. Enter hana credentials and choose database
4. See error message
5. See in network tab the exception
```java
java.lang.ClassCastException: class org.apache.commons.dbcp2.BasicDataSource cannot be cast to class org.eclipse.dirigible.database.api.wrappers.WrappedDataSource (org.apache.commons.dbcp2.BasicDataSource and org.eclipse.dirigible.database.api.wrappers.WrappedDataSource are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @5a915c43)
```

**Expected behavior**
1. DUs are successfully listed
2. In case of an exception, it must be logged in the console, now it isn't

**Additional context**
Java version in container is 11
```
# java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment 18.9 (build 11.0.4+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11, mixed mode)
```

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/pull/1420, will be fixed with the next version of Eclipse Dirigible.
