### ISSUE TITLE
Keep synchronisation state when parsing of the artefacts fails

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#972]
This is the second part of:
- #944 

----

Keep synchronisation state is not implemented in case of errors during parsing artefacts yet.

**Target**

- [ ]   .hdbstructure
- [ ]   .hdbti
- [ ]   .xsaccess
- [ ]   .xsapp
- [ ]   .xshttpdest
- [ ]   .xsjob
- [ ]   .xsjs
- [ ]   .xsjslib
- [ ]   .xsodata
- [ ]   .xsprivileges
- [ ]   .xssecurestore

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
