### ISSUE TITLE
[Releng] Docker with unprivileged user

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#988]
By default, tomcat image runs java process as `root`, which may pose potential risks for container escape.

Switching to unprivileged user adds additional barrier so attacker will have to implement privilege escalation attack first as typically container escape attack requires root level access to be gained first.

**Comment by ThuF** [comment]
Change reverted with #999, better way to restrict access to be implemented.

**Comment by krasimirdermendzhiev** [comment]
Closed with Fix: #1026
