### ISSUE TITLE
[Migration] Migrated projects are not visible in the workspace

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#996]
Due to [an issue in the Dirigible](https://github.com/eclipse/dirigible/issues/1439) when migrating some projects, they are not visible in the Workspace perspective.

This issue should be closed once [the Dirigible fix](https://github.com/eclipse/dirigible/pull/1440) is merged and a new release is made and the XSK updated.

**Comment by ThuF** [comment]
Fixed with **6.1.17**, to be tested by @vmutafov .

**Comment by vmutafov** [comment]
Closing as I've tested and it's ok now
